/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -c TrayManager -p dbustraymanager com.deepin.dde.TrayManager.xml
 *
 * qdbusxml2cpp is Copyright (C) 2015 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef DBUSTRAYMANAGER_H_1435726109
#define DBUSTRAYMANAGER_H_1435726109

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>
#include <QDBusMetaType>

typedef QList<uint> QUintList;

Q_DECLARE_METATYPE(QUintList)

/*
 * Proxy class for interface com.deepin.dde.TrayManager
 */
class TrayManager: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "com.deepin.dde.TrayManager"; }

public:
    TrayManager(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~TrayManager();

    Q_PROPERTY(QUintList TrayIcons READ trayIcons)
    inline QUintList trayIcons() const
    { return qvariant_cast< QUintList >(property("TrayIcons")); }

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<> EnableNotification(uint in0, bool in1)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(in0) << QVariant::fromValue(in1);
        return asyncCallWithArgumentList(QStringLiteral("EnableNotification"), argumentList);
    }

    inline QDBusPendingReply<QString> GetName(uint in0)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(in0);
        return asyncCallWithArgumentList(QStringLiteral("GetName"), argumentList);
    }

    inline QDBusPendingReply<bool> Manage()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("Manage"), argumentList);
    }

    inline QDBusPendingReply<> RequireManageTrayIcons()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("RequireManageTrayIcons"), argumentList);
    }

    inline QDBusPendingReply<> RetryManager()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("RetryManager"), argumentList);
    }

    inline QDBusPendingReply<bool> Unmanage()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("Unmanage"), argumentList);
    }

Q_SIGNALS: // SIGNALS
    void Added(uint in0);
    void Changed(uint in0);
    void Removed(uint in0);
};

namespace com {
  namespace deepin {
    namespace dde {
      typedef ::TrayManager TrayManager;
    }
  }
}
#endif
