// This file is automatically generated, please don't edit manully.
package main

func generalIsKeyInSettingField(field, key string) bool {
	if isVirtualKey(field, key) {
		return true
	}
	switch field {
	default:
		Logger.Warning("invalid field name", field)
	case field8021x:
		return isKeyInSetting8021x(key)
	case fieldConnection:
		return isKeyInSettingConnection(key)
	case fieldIPv4:
		return isKeyInSettingIp4Config(key)
	case fieldIPv6:
		return isKeyInSettingIp6Config(key)
	case fieldWired:
		return isKeyInSettingWired(key)
	case fieldWireless:
		return isKeyInSettingWireless(key)
	case fieldWirelessSecurity:
		return isKeyInSettingWirelessSecurity(key)
	case fieldPppoe:
		return isKeyInSettingPppoe(key)
	case fieldPpp:
		return isKeyInSettingPpp(key)
	}
	return false
}

func generalGetSettingKeyType(field, key string) (t ktype) {
	if isVirtualKey(field, key) {
		t = getSettingVkKeyType(field, key)
		return
	}
	switch field {
	default:
		Logger.Warning("invalid field name", field)
	case field8021x:
		t = getSetting8021xKeyType(key)
	case fieldConnection:
		t = getSettingConnectionKeyType(key)
	case fieldIPv4:
		t = getSettingIp4ConfigKeyType(key)
	case fieldIPv6:
		t = getSettingIp6ConfigKeyType(key)
	case fieldWired:
		t = getSettingWiredKeyType(key)
	case fieldWireless:
		t = getSettingWirelessKeyType(key)
	case fieldWirelessSecurity:
		t = getSettingWirelessSecurityKeyType(key)
	case fieldPppoe:
		t = getSettingPppoeKeyType(key)
	case fieldPpp:
		t = getSettingPppKeyType(key)
	}
	return
}

func generalGetSettingAvailableKeys(data _ConnectionData, field string) (keys []string) {
	switch field {
	case field8021x:
		keys = getSetting8021xAvailableKeys(data)
	case fieldConnection:
		keys = getSettingConnectionAvailableKeys(data)
	case fieldIPv4:
		keys = getSettingIp4ConfigAvailableKeys(data)
	case fieldIPv6:
		keys = getSettingIp6ConfigAvailableKeys(data)
	case fieldWired:
		keys = getSettingWiredAvailableKeys(data)
	case fieldWireless:
		keys = getSettingWirelessAvailableKeys(data)
	case fieldWirelessSecurity:
		keys = getSettingWirelessSecurityAvailableKeys(data)
	case fieldPppoe:
		keys = getSettingPppoeAvailableKeys(data)
	case fieldPpp:
		keys = getSettingPppAvailableKeys(data)
	}
	return
}

func generalGetSettingAvailableValues(data _ConnectionData, field, key string) (values []string, customizable bool) {
	if isVirtualKey(field, key) {
		values = generalGetSettingVkAvailableValues(field, key)
		return
	}
	switch field {
	case field8021x:
		values, customizable = getSetting8021xAvailableValues(data, key)
	case fieldConnection:
		values, customizable = getSettingConnectionAvailableValues(key)
	case fieldIPv4:
		values, customizable = getSettingIp4ConfigAvailableValues(data, key)
	case fieldIPv6:
		values, customizable = getSettingIp6ConfigAvailableValues(key)
	case fieldWired:
		values, customizable = getSettingWiredAvailableValues(key)
	case fieldWireless:
		values, customizable = getSettingWirelessAvailableValues(key)
	case fieldWirelessSecurity:
		values, customizable = getSettingWirelessSecurityAvailableValues(key)
	case fieldPppoe:
		values, customizable = getSettingPppoeAvailableValues(key)
	case fieldPpp:
		values, customizable = getSettingPppAvailableValues(key)
	}
	return
}

func generalCheckSettingValues(data _ConnectionData, field string) (errs map[string]string) {
	switch field {
	default:
		Logger.Error("updatePropErrors: invalid field name", field)
	case field8021x:
		errs = checkSetting8021xValues(data)
	case fieldConnection:
		errs = checkSettingConnectionValues(data)
	case fieldIPv4:
		errs = checkSettingIp4ConfigValues(data)
	case fieldIPv6:
		errs = checkSettingIp6ConfigValues(data)
	case fieldWired:
		errs = checkSettingWiredValues(data)
	case fieldWireless:
		errs = checkSettingWirelessValues(data)
	case fieldWirelessSecurity:
		errs = checkSettingWirelessSecurityValues(data)
	case fieldPppoe:
		errs = checkSettingPppoeValues(data)
	case fieldPpp:
		errs = checkSettingPppValues(data)
	}
	return
}

func generalGetSettingKeyJSON(data _ConnectionData, field, key string) (valueJSON string) {
	if isVirtualKey(field, key) {
		valueJSON = generalGetVirtualKeyJSON(data, field, key)
		return
	}
	switch field {
	default:
		Logger.Warning("invalid field name", field)
	case field8021x:
		valueJSON = generalGetSetting8021xKeyJSON(data, key)
	case fieldConnection:
		valueJSON = generalGetSettingConnectionKeyJSON(data, key)
	case fieldIPv4:
		valueJSON = generalGetSettingIp4ConfigKeyJSON(data, key)
	case fieldIPv6:
		valueJSON = generalGetSettingIp6ConfigKeyJSON(data, key)
	case fieldWired:
		valueJSON = generalGetSettingWiredKeyJSON(data, key)
	case fieldWireless:
		valueJSON = generalGetSettingWirelessKeyJSON(data, key)
	case fieldWirelessSecurity:
		valueJSON = generalGetSettingWirelessSecurityKeyJSON(data, key)
	case fieldPppoe:
		valueJSON = generalGetSettingPppoeKeyJSON(data, key)
	case fieldPpp:
		valueJSON = generalGetSettingPppKeyJSON(data, key)
	}
	return
}

func generalSetSettingKeyJSON(data _ConnectionData, field, key, valueJSON string) {
	if isVirtualKey(field, key) {
		generalSetVirtualKeyJSON(data, field, key, valueJSON)
		return
	}
	switch field {
	default:
		Logger.Warning("invalid field name", field)
	case field8021x:
		generalSetSetting8021xKeyJSON(data, key, valueJSON)
	case fieldConnection:
		generalSetSettingConnectionKeyJSON(data, key, valueJSON)
	case fieldIPv4:
		generalSetSettingIp4ConfigKeyJSON(data, key, valueJSON)
	case fieldIPv6:
		generalSetSettingIp6ConfigKeyJSON(data, key, valueJSON)
	case fieldWired:
		generalSetSettingWiredKeyJSON(data, key, valueJSON)
	case fieldWireless:
		generalSetSettingWirelessKeyJSON(data, key, valueJSON)
	case fieldWirelessSecurity:
		generalSetSettingWirelessSecurityKeyJSON(data, key, valueJSON)
	case fieldPppoe:
		generalSetSettingPppoeKeyJSON(data, key, valueJSON)
	case fieldPpp:
		generalSetSettingPppKeyJSON(data, key, valueJSON)
	}
}

func getSettingKeyDefaultValueJSON(field, key string) (valueJSON string) {
	switch field {
	default:
		Logger.Warning("invalid field name", field)
	case field8021x:
		valueJSON = getSetting8021xKeyDefaultValueJSON(key)
	case fieldConnection:
		valueJSON = getSettingConnectionKeyDefaultValueJSON(key)
	case fieldIPv4:
		valueJSON = getSettingIp4ConfigKeyDefaultValueJSON(key)
	case fieldIPv6:
		valueJSON = getSettingIp6ConfigKeyDefaultValueJSON(key)
	case fieldWired:
		valueJSON = getSettingWiredKeyDefaultValueJSON(key)
	case fieldWireless:
		valueJSON = getSettingWirelessKeyDefaultValueJSON(key)
	case fieldWirelessSecurity:
		valueJSON = getSettingWirelessSecurityKeyDefaultValueJSON(key)
	case fieldPppoe:
		valueJSON = getSettingPppoeKeyDefaultValueJSON(key)
	case fieldPpp:
		valueJSON = getSettingPppKeyDefaultValueJSON(key)
	}
	return
}
