#!/bin/sh

set -e

USER=deepin-daemon

if [ "$1" = configure ];then
    adduser --system \
        --quiet \
        --no-create-home \
        --disabled-password \
        --group "$USER"

    if [ -f /etc/systemd/logind.conf ];then
        sed -i 's/^#\?HandlePowerKey=.*$/HandlePowerKey=ignore/g' /etc/systemd/logind.conf || true
        sed -i 's/^#\?HandleLidSwitch=.*$/HandleLidSwitch=ignore/g' /etc/systemd/logind.conf || true
    fi

fi
if [ -f /usr/share/fcitx/addon/fcitx-xkb.conf ];then
    sed -i 's/Enabled=.*$/Enabled=False/' /usr/share/fcitx/addon/fcitx-xkb.conf || true
fi

command=/usr/lib/deepin-daemon/theme-thumb-tool
target_dir=/usr/share/personalization/thumbnail
if [ -x $command ];then
	$command --gtk $target_dir 2> /dev/null || echo "Error handling --gtk"
	$command --icon $target_dir 2> /dev/null || echo "Error handling --icon"
	$command --cursor $target_dir 2> /dev/null || echo "Error handling --cursor"
	$command --background $target_dir 2> /dev/null || echo "Error handling --background"
fi
if [ ! -e /var/cache/deepin/mark-setup-network-services ]; then
    update-rc.d ipsec disable
    update-rc.d xl2tpd disable
    update-rc.d openvpn disable
    mkdir -p /var/cache/deepin 
    touch /var/cache/deepin/mark-setup-network-services
fi
#DEBHELPER#
