#!/bin/sh
set -e

if [ "$1" = "remove" ];then
    update-alternatives --remove x-terminal-emulator /usr/lib/deepin-daemon/default-terminal
    pam-auth-update --package --remove deepin-auth
fi

#DEBHELPER#
