// Code generated by "dbusutil-gen -type Manager -import pkg.deepin.io/lib/dbus1 manager.go"; DO NOT EDIT.

package fprintd

import (
	"pkg.deepin.io/lib/dbus1"
)

func (v *Manager) setPropDevices(value []dbus.ObjectPath) {
	v.Devices = value
	v.emitPropChangedDevices(value)
}

func (v *Manager) emitPropChangedDevices(value []dbus.ObjectPath) error {
	return v.service.EmitPropertyChanged(v, "Devices", value)
}
