package datetime

import . "dlib/gettext"

var zoneCityMap map[string]string

func initZoneCityMap() {
	zoneCityMap = map[string]string{
		"Africa/Abidjan":                   Tr("Côte d'Ivoire (UTC+00) Abidjan"),
		"Africa/Accra":                     Tr("Ghana (UTC+00) Accra"),
		"Africa/Addis_Ababa":               Tr("Ethiopia (UTC+03) Addis Ababa"),
		"Africa/Algiers":                   Tr("Algeria (UTC+01) Algiers"),
		"Africa/Asmara":                    Tr("Eritrea (UTC+03) Asmara"),
		"Africa/Asmera":                    Tr("Eritrea (UTC+03) Asmera"),
		"Africa/Bamako":                    Tr("Mali (UTC+00) Bamako"),
		"Africa/Bangui":                    Tr("Central African Republic (UTC+01) Bangui"),
		"Africa/Banjul":                    Tr("The Gambia (UTC+00) Banjul"),
		"Africa/Bissau":                    Tr("Guinea-Bissau (UTC+00) Bissau"),
		"Africa/Blantyre":                  Tr("Malawi (UTC+02) Blantyre"),
		"Africa/Brazzaville":               Tr("Congo (UTC+01) Brazzaville"),
		"Africa/Bujumbura":                 Tr("Burundi (UTC+02) Bujumbura"),
		"Africa/Cairo":                     Tr("Egypt (UTC+02) Cairo"),
		"Africa/Casablanca":                Tr("Morocco (UTC+00) Casablanca"),
		"Africa/Ceuta":                     Tr("Spain (UTC+01) Ceuta"),
		"Africa/Conakry":                   Tr("Guinea (UTC+00) Conakry"),
		"Africa/Dakar":                     Tr("Senegal (UTC+00) Dakar"),
		"Africa/Dar_es_Salaam":             Tr("Tanzania (UTC+03) Dar es Salaam"),
		"Africa/Djibouti":                  Tr("Djibouti (UTC+03) Djibouti"),
		"Africa/Douala":                    Tr("Cameroon (UTC+01) Douala"),
		"Africa/El_Aaiun":                  Tr("Western Sahara (UTC+00) El Aaiun"),
		"Africa/Freetown":                  Tr("Sierra Leone (UTC+00) Freetown"),
		"Africa/Gaborone":                  Tr("Botswana (UTC+02) Gaborone"),
		"Africa/Harare":                    Tr("Zimbabwe (UTC+02) Harare"),
		"Africa/Johannesburg":              Tr("South Africa (UTC+02) Johannesburg"),
		"Africa/Juba":                      Tr("South Sudan (UTC+03) Juba"),
		"Africa/Kampala":                   Tr("Uganda (UTC+03) Kampala"),
		"Africa/Khartoum":                  Tr("Sudan (UTC+03) Khartoum"),
		"Africa/Kigali":                    Tr("Rwanda (UTC+02) Kigali"),
		"Africa/Kinshasa":                  Tr("Democratic Republic of the Congo (UTC+01) Kinshasa"),
		"Africa/Lagos":                     Tr("Nigeria (UTC+01) Lagos"),
		"Africa/Libreville":                Tr("Gabon (UTC+01) Libreville"),
		"Africa/Lome":                      Tr("Togo (UTC+00) Lome"),
		"Africa/Luanda":                    Tr("Angola (UTC+01) Luanda"),
		"Africa/Lubumbashi":                Tr("Democratic Republic of the Congo (UTC+02) Lubumbashi"),
		"Africa/Lusaka":                    Tr("Zambia (UTC+02) Lusaka"),
		"Africa/Malabo":                    Tr("Equatorial Guinea (UTC+01) Malabo"),
		"Africa/Maputo":                    Tr("Mozambique (UTC+02) Maputo"),
		"Africa/Maseru":                    Tr("Lesotho (UTC+02) Maseru"),
		"Africa/Mbabane":                   Tr("Swaziland (UTC+02) Mbabane"),
		"Africa/Mogadishu":                 Tr("Somalia (UTC+03) Mogadishu"),
		"Africa/Monrovia":                  Tr("Liberia (UTC+00) Monrovia"),
		"Africa/Nairobi":                   Tr("Kenya (UTC+03) Nairobi"),
		"Africa/Ndjamena":                  Tr("Chad (UTC+01) Ndjamena"),
		"Africa/Niamey":                    Tr("Niger (UTC+01) Niamey"),
		"Africa/Nouakchott":                Tr("Mauritania (UTC+00) Nouakchott"),
		"Africa/Ouagadougou":               Tr("Burkina Faso (UTC+00) Ouagadougou"),
		"Africa/Porto-Novo":                Tr("Benin (UTC+01) Porto Novo"),
		"Africa/Sao_Tome":                  Tr("São Tomé and Príncipe (UTC+00) Sao Tome"),
		"Africa/Timbuktu":                  Tr("Mali (UTC+00) Timbuktu"),
		"Africa/Tripoli":                   Tr("Libya (UTC+02) Tripoli"),
		"Africa/Tunis":                     Tr("Tunisia (UTC+01) Tunis"),
		"Africa/Windhoek":                  Tr("Namibia (UTC+01) Windhoek"),
		"America/Adak":                     Tr("USA (UTC-10) Adak"),
		"America/Anchorage":                Tr("USA (UTC-09) Anchorage"),
		"America/Anguilla":                 Tr("USA (UTC-04) Anguilla"),
		"America/Antigua":                  Tr("USA (UTC-04) Antigua"),
		"America/Araguaina":                Tr("USA (UTC-03) Araguaina"),
		"America/Argentina/Buenos_Aires":   Tr("Argentina (UTC-03) Buenos Aires"),
		"America/Argentina/Catamarca":      Tr("Argentina (UTC-03) Catamarca"),
		"America/Argentina/ComodRivadavia": Tr("Argentina (UTC-03) ComodRivadavia"),
		"America/Argentina/Cordoba":        Tr("Argentina (UTC-03) Cordoba"),
		"America/Argentina/Jujuy":          Tr("Argentina (UTC-03) Jujuy"),
		"America/Argentina/La_Rioja":       Tr("Argentina (UTC-03) La Rioja"),
		"America/Argentina/Mendoza":        Tr("Argentina (UTC-03) Mendoza"),
		"America/Argentina/Rio_Gallegos":   Tr("Argentina (UTC-03) Rio Gallegos"),
		"America/Argentina/Salta":          Tr("Argentina (UTC-03) Salta"),
		"America/Argentina/San_Juan":       Tr("Argentina (UTC-03) San Juan"),
		"America/Argentina/San_Luis":       Tr("Argentina (UTC-03) San Luis"),
		"America/Argentina/Tucuman":        Tr("Argentina (UTC-03) Tucuman"),
		"America/Argentina/Ushuaia":        Tr("Argentina (UTC-03) Ushuaia"),
		"America/Aruba":                    Tr("USA (UTC-04) Aruba"),
		"America/Asuncion":                 Tr("USA (UTC-04) Asuncion"),
		"America/Atikokan":                 Tr("Canada (UTC-05) Atikokan"),
		"America/Atka":                     Tr("USA (UTC-10) Atka"),
		"America/Bahia":                    Tr("Brazil (UTC-03) Bahia"),
		"America/Bahia_Banderas":           Tr("Mexico (UTC-06) Bahia Banderas"),
		"America/Barbados":                 Tr("USA (UTC-04) Barbados"),
		"America/Belem":                    Tr("USA (UTC-03) Belem"),
		"America/Belize":                   Tr("USA (UTC-06) Belize"),
		"America/Boa_Vista":                Tr("USA (UTC-04) Boa Vista"),
		"America/Bogota":                   Tr("USA (UTC-05) Bogota"),
		"America/Boise":                    Tr("USA (UTC-07) Boise"),
		"America/Buenos_Aires":             Tr("Argentina (UTC-03) Buenos Aires"),
		"America/Cambridge_Bay":            Tr("USA (UTC-07) Cambridge Bay"),
		"America/Campo_Grande":             Tr("USA (UTC-04) Campo Grande"),
		"America/Cancun":                   Tr("USA (UTC-06) Cancun"),
		"America/Caracas":                  Tr("Ecuador (UTC-03) Caracas"),
		"America/Cayenne":                  Tr("USA (UTC-03) Cayenne"),
		"America/Cayman":                   Tr("USA (UTC-05) Cayman"),
		"America/Chicago":                  Tr("USA (UTC-06) Chicago"),
		"America/Chihuahua":                Tr("Mexico (UTC-07) Chihuahua"),
		"America/Coral_Harbour":            Tr("USA (UTC-05) Coral Harbour"),
		"America/Cordoba":                  Tr("USA (UTC-03) Cordoba"),
		"America/Costa_Rica":               Tr("USA (UTC-06) Costa Rica"),
		"America/Creston":                  Tr("USA (UTC-07) Creston"),
		"America/Cuiaba":                   Tr("USA (UTC-04) Cuiaba"),
		"America/Curacao":                  Tr("USA (UTC-04) Curacao"),
		"America/Dawson":                   Tr("USA (UTC-08) Dawson"),
		"America/Dawson_Creek":             Tr("USA (UTC-07) Dawson Creek"),
		"America/Denver":                   Tr("USA (UTC-07) Denver"),
		"America/Detroit":                  Tr("USA (UTC-05) Detroit"),
		"America/Dominica":                 Tr("USA (UTC-04) Dominica"),
		"America/Edmonton":                 Tr("USA (UTC-07) Edmonton"),
		"America/Eirunepe":                 Tr("Brazil (UTC-04) Eirunepe"),
		"America/El_Salvador":              Tr("USA (UTC-06) El Salvador"),
		"America/Ensenada":                 Tr("USA (UTC-08) Ensenada"),
		"America/Fort_Wayne":               Tr("USA (UTC-05) Fort Wayne"),
		"America/Fortaleza":                Tr("USA (UTC-03) Fortaleza"),
		"America/Glace_Bay":                Tr("USA (UTC-04) Glace Bay"),
		"America/Godthab":                  Tr("Greenland (UTC-03) Godthab"),
		"America/Goose_Bay":                Tr("USA (UTC-04) Goose Bay"),
		"America/Grand_Turk":               Tr("USA (UTC-05) Grand Turk"),
		"America/Grenada":                  Tr("USA (UTC-04) Grenada"),
		"America/Guadeloupe":               Tr("Mexico (UTC-04) Guadeloupe"),
		"America/Guatemala":                Tr("Mexico (UTC-06) Guatemala"),
		"America/Guayaquil":                Tr("Ecuador (UTC-05) Guayaquil"),
		"America/Guyana":                   Tr("Mexico (UTC-04) Guyana"),
		"America/Halifax":                  Tr("USA (UTC-04) Halifax"),
		"America/Havana":                   Tr("USA (UTC-05) Havana"),
		"America/Hermosillo":               Tr("USA (UTC-07) Hermosillo"),
		"America/Indiana/Indianapolis":     Tr("USA (UTC-05) Indianapolis"),
		"America/Indiana/Knox":             Tr("USA (UTC-06) Knox"),
		"America/Indiana/Marengo":          Tr("USA (UTC-05) Marengo"),
		"America/Indiana/Petersburg":       Tr("USA (UTC-05) Petersburg"),
		"America/Indiana/Tell_City":        Tr("USA (UTC-06) Tell City"),
		"America/Indiana/Vevay":            Tr("USA (UTC-05) Vevay"),
		"America/Indiana/Vincennes":        Tr("USA (UTC-05) Vincennes"),
		"America/Indiana/Winamac":          Tr("USA (UTC-05) Winamac"),
		"America/Indianapolis":             Tr("USA (UTC-05) Indianapolis"),
		"America/Inuvik":                   Tr("Canada (UTC-07) Inuvik"),
		"America/Iqaluit":                  Tr("Canada (UTC-05) Iqaluit"),
		"America/Jamaica":                  Tr("USA (UTC-05) Jamaica"),
		"America/Jujuy":                    Tr("Argentina (UTC-03) Jujuy"),
		"America/Juneau":                   Tr("USA (UTC-09) Juneau"),
		"America/Kentucky/Louisville":      Tr("USA (UTC-05) Louisville"),
		"America/Kentucky/Monticello":      Tr("USA (UTC-05) Monticello"),
		"America/Knox_IN":                  Tr("USA (UTC-06) Knox IN"),
		"America/Kralendijk":               Tr("Caribbean Netherlands (UTC-04) Kralendijk"),
		"America/La_Paz":                   Tr("USA (UTC-04) La Paz"),
		"America/Lima":                     Tr("USA (UTC-05) Lima"),
		"America/Los_Angeles":              Tr("USA (UTC-08) Los Angeles"),
		"America/Louisville":               Tr("USA (UTC-05) Louisville"),
		"America/Lower_Princes":            Tr("Canada (UTC-04) Lower Princes"),
		"America/Maceio":                   Tr("Brazil (UTC-03) Maceio"),
		"America/Managua":                  Tr("Mexico (UTC-06) Managua"),
		"America/Manaus":                   Tr("USA (UTC-04) Manaus"),
		"America/Marigot":                  Tr("USA (UTC-04) Marigot"),
		"America/Martinique":               Tr("USA (UTC-04) Martinique"),
		"America/Matamoros":                Tr("Mexico (UTC-06) Matamoros"),
		"America/Mazatlan":                 Tr("USA (UTC-07) Mazatlan"),
		"America/Mendoza":                  Tr("USA (UTC-03) Mendoza"),
		"America/Menominee":                Tr("USA (UTC-06) Menominee"),
		"America/Merida":                   Tr("USA (UTC-06) Merida"),
		"America/Metlakatla":               Tr("USA (UTC-08) Metlakatla"),
		"America/Mexico_City":              Tr("USA (UTC-06) Mexico City"),
		"America/Miquelon":                 Tr("USA (UTC-03) Miquelon"),
		"America/Moncton":                  Tr("Canada (UTC-04) Moncton"),
		"America/Monterrey":                Tr("USA (UTC-06) Monterrey"),
		"America/Montevideo":               Tr("USA (UTC-03) Montevideo"),
		"America/Montreal":                 Tr("USA (UTC-05) Montreal"),
		"America/Montserrat":               Tr("USA (UTC-04) Montserrat"),
		"America/Nassau":                   Tr("USA (UTC-05) Nassau"),
		"America/New_York":                 Tr("USA (UTC-05) New York"),
		"America/Nipigon":                  Tr("Canada (UTC-05) Nipigon"),
		"America/Nome":                     Tr("USA (UTC-09) Nome"),
		"America/Noronha":                  Tr("Brazil (UTC-02) Noronha"),
		"America/North_Dakota/Beulah":      Tr("USA (UTC-06) Beulah"),
		"America/North_Dakota/Center":      Tr("USA (UTC-06) Center"),
		"America/North_Dakota/New_Salem":   Tr("USA (UTC-06) New Salem"),
		"America/Ojinaga":                  Tr("Mexico (UTC-07) Ojinaga"),
		"America/Panama":                   Tr("USA (UTC-05) Panama"),
		"America/Paramaribo":               Tr("Mexico (UTC-03) Paramaribo"),
		"America/Phoenix":                  Tr("USA (UTC-07) Phoenix"),
		"America/Port_of_Spain":            Tr("USA (UTC-04) Port of Spain"),
		"America/Port-au-Prince":           Tr("USA (UTC-05) Port au Prince"),
		"America/Porto_Acre":               Tr("Brazil (UTC-05) Porto Acre"),
		"America/Porto_Velho":              Tr("USA (UTC-04) Porto Velho"),
		"America/Puerto_Rico":              Tr("USA (UTC-04) Puerto Rico"),
		"America/Rainy_River":              Tr("USA (UTC-06) Rainy River"),
		"America/Recife":                   Tr("USA (UTC-03) Recife"),
		"America/Regina":                   Tr("USA (UTC-06) Regina"),
		"America/Resolute":                 Tr("USA (UTC-06) Resolute"),
		"America/Rio_Branco":               Tr("USA (UTC-05) Rio Branco"),
		"America/Rosario":                  Tr("USA (UTC-03) Rosario"),
		"America/Santa_Isabel":             Tr("USA (UTC-08) Santa Isabel"),
		"America/Santarem":                 Tr("USA (UTC-03) Santarem"),
		"America/Santiago":                 Tr("USA (UTC-04) Santiago"),
		"America/Santo_Domingo":            Tr("USA (UTC-04) Santo Domingo"),
		"America/Sao_Paulo":                Tr("USA (UTC-03) Sao Paulo"),
		"America/Shiprock":                 Tr("USA (UTC-07) Shiprock"),
		"America/Sitka":                    Tr("USA (UTC-09) Sitka"),
		"America/St_Barthelemy":            Tr("USA (UTC-04) St Barthelemy"),
		"America/St_Johns":                 Tr("USA (UTC-04) St Johns"),
		"America/St_Lucia":                 Tr("USA (UTC-04) St Lucia"),
		"America/St_Thomas":                Tr("USA (UTC-04) St Thomas"),
		"America/St_Vincent":               Tr("USA (UTC-04) St Vincent"),
		"America/Swift_Current":            Tr("Canada (UTC-06) Swift Current"),
		"America/Tegucigalpa":              Tr("Ecuador (UTC-06) Tegucigalpa"),
		"America/Thule":                    Tr("USA (UTC-04) Thule"),
		"America/Thunder_Bay":              Tr("USA (UTC-05) Thunder Bay"),
		"America/Tijuana":                  Tr("Mexico (UTC-08) Tijuana"),
		"America/Toronto":                  Tr("Canada (UTC-05) Toronto"),
		"America/Tortola":                  Tr("USA (UTC-04) Tortola"),
		"America/Vancouver":                Tr("USA (UTC-08) Vancouver"),
		"America/Virgin":                   Tr("USA (UTC-04) Virgin"),
		"America/Whitehorse":               Tr("USA (UTC-08) Whitehorse"),
		"America/Winnipeg":                 Tr("Canada (UTC-06) Winnipeg"),
		"America/Yakutat":                  Tr("USA (UTC-09) Yakutat"),
		"America/Yellowknife":              Tr("USA (UTC-07) Yellowknife"),
		"Antarctica/Casey":                 Tr("Antarctica (UTC+11) Casey"),
		"Antarctica/Davis":                 Tr("Antarctica (UTC+05) Davis"),
		"Antarctica/DumontDUrville":        Tr("Antarctica (UTC+10) DumontDUrville"),
		"Antarctica/Mawson":                Tr("Antarctica (UTC+05) Mawson"),
		"Antarctica/McMurdo":               Tr("Antarctica (UTC+12) McMurdo"),
		"Antarctica/Palmer":                Tr("Antarctica (UTC-04) Palmer"),
		"Antarctica/Rothera":               Tr("Antarctica (UTC-03) Rothera"),
		"Antarctica/South_Pole":            Tr("Antarctica (UTC+12) South Pole"),
		"Antarctica/Vostok":                Tr("Antarctica (UTC+06) Vostok"),
		"Arctic/Longyearbyen":              Tr("Svalbard and Jan Mayen (UTC+01) Longyearbyen"),
		"Asia/Aden":                        Tr("Yemen (UTC+03) Aden"),
		"Asia/Almaty":                      Tr("Kazakhstan (UTC+06) Almaty"),
		"Asia/Amman":                       Tr("Jordan (UTC+02) Amman"),
		"Asia/Anadyr":                      Tr("Russia (UTC+12) Anadyr"),
		"Asia/Aqtau":                       Tr("Kazakhstan (UTC+05) Aqtau"),
		"Asia/Aqtobe":                      Tr("Kazakhstan (UTC+05) Aqtobe"),
		"Asia/Ashgabat":                    Tr("Turkmenistan (UTC+05) Ashgabat"),
		"Asia/Ashkhabad":                   Tr("Turkmenistan (UTC+05) Ashkhabad"),
		"Asia/Baghdad":                     Tr("Iraq (UTC+03) Baghdad"),
		"Asia/Bahrain":                     Tr("Bahrain (UTC+03) Bahrain"),
		"Asia/Baku":                        Tr("Azerbaijan (UTC+04) Baku"),
		"Asia/Bangkok":                     Tr("Thailand (UTC+07) Bangkok"),
		"Asia/Beirut":                      Tr("Lebanon (UTC+02) Beirut"),
		"Asia/Bishkek":                     Tr("Kyrgyzstan (UTC+06) Bishkek"),
		"Asia/Brunei":                      Tr("Brunei (UTC+08) Brunei"),
		"Asia/Calcutta":                    Tr("India (UTC+08) Calcutta"),
		"Asia/Chongqing":                   Tr("China (UTC+08) Chongqing"),
		"Asia/Chungking":                   Tr("China (UTC+08) Chungking"),
		"Asia/Colombo":                     Tr("Sri Lanka (UTC+06) Colombo"),
		"Asia/Damascus":                    Tr("Syria (UTC+02) Damascus"),
		"Asia/Dhaka":                       Tr("Bangladesh (UTC+06) Dhaka"),
		"Asia/Dili":                        Tr("Timor-Leste (UTC+09) Dili"),
		"Asia/Dubai":                       Tr("Dubai - United Arab Emirates (UTC+04) Dubai"),
		"Asia/Dushanbe":                    Tr("Tajikistan (UTC+05) Dushanbe"),
		"Asia/Gaza":                        Tr("Gaza (UTC+02) Gaza"),
		"Asia/Harbin":                      Tr("China (UTC+08) Harbin"),
		"Asia/Hebron":                      Tr("Hebron (UTC+02) Hebron"),
		"Asia/Ho_Chi_Minh":                 Tr("Vietnam (UTC+07) Ho Chi Minh"),
		"Asia/Hong_Kong":                   Tr("Hong Kong (UTC+08) Hong Kong"),
		"Asia/Hovd":                        Tr("Mongolia (UTC+07) Hovd"),
		"Asia/Irkutsk":                     Tr("Russia (UTC+09) Irkutsk"),
		"Asia/Istanbul":                    Tr("Turkey (UTC+02) Istanbul"),
		"Asia/Jakarta":                     Tr("Indonesia (UTC+07) Jakarta"),
		"Asia/Jayapura":                    Tr("India (UTC+09) Jayapura"),
		"Asia/Jerusalem":                   Tr("Israel (UTC+02) Jerusalem"),
		"Asia/Kabul":                       Tr("Afghanistan (UTC+12) Kabul"),
		"Asia/Karachi":                     Tr("Pakistan (UTC+05) Karachi"),
		"Asia/Kashgar":                     Tr("China (UTC+08) Kashgar"),
		"Asia/Kathmandu":                   Tr("Nepal (UTC+08) Kathmandu"),
		"Asia/Kuala_Lumpur":                Tr("Malaysia (UTC+08) Kuala Lumpur"),
		"Asia/Kuching":                     Tr("Malaysia (UTC+08) Kuching"),
		"Asia/Kuwait":                      Tr("Kuwait (UTC+03) Kuwait"),
		"Asia/Macao":                       Tr("Macau (UTC+08) Macao"),
		"Asia/Macau":                       Tr("Macau (UTC+08) Macau"),
		"Asia/Magadan":                     Tr("Russia (UTC+12) Magadan"),
		"Asia/Makassar":                    Tr("Indonesia (UTC+08) Makassar"),
		"Asia/Manila":                      Tr("Philippines (UTC+08) Manila"),
		"Asia/Muscat":                      Tr("Oman (UTC+04) Muscat"),
		"Asia/Nicosia":                     Tr("Nicosia (UTC+02) Nicosia"),
		"Asia/Novokuznetsk":                Tr("Russia (UTC+07) Novokuznetsk"),
		"Asia/Novosibirsk":                 Tr("Russia (UTC+07) Novosibirsk"),
		"Asia/Omsk":                        Tr("Russia (UTC+07) Omsk"),
		"Asia/Oral":                        Tr("Kazakhstan (UTC+05) Oral"),
		"Asia/Phnom_Penh":                  Tr("Cambodia (UTC+07) Phnom Penh"),
		"Asia/Pontianak":                   Tr("Indonesia (UTC+07) Pontianak"),
		"Asia/Pyongyang":                   Tr("North Korea (UTC+09) Pyongyang"),
		"Asia/Qatar":                       Tr("Qatar (UTC+03) Qatar"),
		"Asia/Qyzylorda":                   Tr("Kazakhstan (UTC+06) Qyzylorda"),
		"Asia/Rangoon":                     Tr("Myanmar (Burma) (UTC+03) Rangoon"),
		"Asia/Saigon":                      Tr("Vietnam (UTC+07) Saigon"),
		"Asia/Sakhalin":                    Tr("Russia (UTC+11) Sakhalin"),
		"Asia/Samarkand":                   Tr("Uzbekistan (UTC+05) Samarkand"),
		"Asia/Seoul":                       Tr("South Korea (UTC+09) Seoul"),
		"Asia/Shanghai":                    Tr("China (UTC+08) Shanghai"),
		"Asia/Beijing":                     Tr("China (UTC+08) Beijing"),
		"Asia/Singapore":                   Tr("Singapore (UTC+08) Singapore"),
		"Asia/Taipei":                      Tr("Taiwan (UTC+08) Taipei"),
		"Asia/Tashkent":                    Tr("Uzbekistan (UTC+05) Tashkent"),
		"Asia/Tbilisi":                     Tr("Georgia (UTC+04) Tbilisi"),
		"Asia/Tehran":                      Tr("Iran (UTC+02) Tehran"),
		"Asia/Thimbu":                      Tr("Bhutan (UTC+06) Thimbu"),
		"Asia/Thimphu":                     Tr("Bhutan (UTC+06) Thimphu"),
		"Asia/Tokyo":                       Tr("Japan (UTC+09) Tokyo"),
		"Asia/Ujung_Pandang":               Tr("Indonesia (UTC+08) Ujung Pandang"),
		"Asia/Ulaanbaatar":                 Tr("Mongolia (UTC+08) Ulaanbaatar"),
		"Asia/Ulan_Bator":                  Tr("Mongolia (UTC+08) Ulan Bator"),
		"Asia/Urumqi":                      Tr("China (UTC+08) Urumqi"),
		"Asia/Vientiane":                   Tr("Laos (UTC+07) Vientiane"),
		"Asia/Vladivostok":                 Tr("Russia (UTC+11) Vladivostok"),
		"Asia/Yakutsk":                     Tr("Russia (UTC+10) Yakutsk"),
		"Asia/Yekaterinburg":               Tr("620000 (UTC+06) Yekaterinburg"),
		"Asia/Yerevan":                     Tr("Armenia (UTC+04) Yerevan"),
		"Atlantic/Bermuda":                 Tr("USA (UTC-04) Bermuda"),
		"Atlantic/Canary":                  Tr("USA (UTC+00) Canary"),
		"Atlantic/Cape_Verde":              Tr("Puerto Rico (UTC-01) Cape Verde"),
		"Atlantic/Madeira":                 Tr("USA (UTC+00) Madeira"),
		"Atlantic/Reykjavik":               Tr("Iceland (UTC+00) Reykjavik"),
		"Atlantic/South_Georgia":           Tr("USA (UTC-02) South Georgia"),
		"Atlantic/St_Helena":               Tr("USA (UTC+00) St Helena"),
		"Atlantic/Stanley":                 Tr("USA (UTC-03) Stanley"),
		"Australia/ACT":                    Tr("Australia (UTC+10) ACT"),
		"Australia/Adelaide":               Tr("Australia (UTC+10) Adelaide"),
		"Australia/Broken_Hill":            Tr("Australia (UTC+10) Broken Hill"),
		"Australia/Currie":                 Tr("Australia (UTC+10) Currie"),
		"Australia/Darwin":                 Tr("Australia (UTC+10) Darwin"),
		"Australia/Lindeman":               Tr("Australia (UTC+10) Lindeman"),
		"Australia/Lord_Howe":              Tr("Australia (UTC+11) Lord Howe"),
		"Australia/Melbourne":              Tr("Australia (UTC+10) Melbourne"),
		"Australia/North":                  Tr("Australia (UTC+10) North"),
		"Australia/Perth":                  Tr("Australia (UTC+08) Perth"),
		"Australia/Queensland":             Tr("Australia (UTC+10) Queensland"),
		"Australia/South":                  Tr("Australia (UTC+10) South"),
		"Australia/Tasmania":               Tr("Australia (UTC+10) Tasmania"),
		"Australia/Victoria":               Tr("Australia (UTC+10) Victoria"),
		"Australia/West":                   Tr("Australia (UTC+08) West"),
		"Australia/Yancowinna":             Tr("Australia (UTC-05) Yancowinna"),
		"Brazil/East":                      Tr("Brazil (UTC-03) East"),
		"Brazil/West":                      Tr("Brazil (UTC-04) West"),
		"Canada/Atlantic":                  Tr("Canada (UTC-04) Atlantic"),
		"Canada/Central":                   Tr("USA (UTC-06) Central"),
		"Canada/Eastern":                   Tr("Canada (UTC-05) Eastern"),
		"Canada/East-Saskatchewan":         Tr("Canada (UTC-06) East Saskatchewan"),
		"Canada/Mountain":                  Tr("Canada (UTC-07) Mountain"),
		"Canada/Newfoundland":              Tr("Canada (UTC-08) Newfoundland"),
		"Canada/Saskatchewan":              Tr("Canada (UTC-06) Saskatchewan"),
		"Canada/Yukon":                     Tr("Canada (UTC-08) Yukon"),
		"CET":                              Tr("USA (UTC+01) CET"),
		"Chile/Continental":                Tr("Chile (UTC-04) Continental"),
		"Chile/EasterIsland":               Tr("Chile (UTC-06) EasterIsland"),
		"Cuba":                             Tr("Cuba (UTC-05) Cuba"),
		"EET":                              Tr("USA (UTC+02) EET"),
		"Egypt":                            Tr("Egypt (UTC+02) Egypt"),
		"Eire":                             Tr("Ireland (UTC+00) Eire"),
		"EST":                              Tr("Uganda (UTC-05) EST"),
		"Europe/Amsterdam":                 Tr("The Netherlands (UTC+01) Amsterdam"),
		"Europe/Andorra":                   Tr("Andorra (UTC+01) Andorra"),
		"Europe/Athens":                    Tr("Greece (UTC+02) Athens"),
		"Europe/Belfast":                   Tr("UK (UTC+00) Belfast"),
		"Europe/Belgrade":                  Tr("Serbia (UTC+01) Belgrade"),
		"Europe/Berlin":                    Tr("Germany (UTC+01) Berlin"),
		"Europe/Bratislava":                Tr("Slovakia (UTC+01) Bratislava"),
		"Europe/Brussels":                  Tr("Belgium (UTC+01) Brussels"),
		"Europe/Bucharest":                 Tr("Romania (UTC+02) Bucharest"),
		"Europe/Budapest":                  Tr("Hungary (UTC+01) Budapest"),
		"Europe/Chisinau":                  Tr("Moldova (UTC+02) Chisinau"),
		"Europe/Copenhagen":                Tr("Denmark (UTC+01) Copenhagen"),
		"Europe/Dublin":                    Tr("Ireland (UTC+00) Dublin"),
		"Europe/Gibraltar":                 Tr("Gibraltar (UTC+01) Gibraltar"),
		"Europe/Guernsey":                  Tr("Guernsey (UTC+00) Guernsey"),
		"Europe/Helsinki":                  Tr("Finland (UTC+02) Helsinki"),
		"Europe/Isle_of_Man":               Tr("Isle of Man (UTC+00) Isle of Man"),
		"Europe/Istanbul":                  Tr("Turkey (UTC+02) Istanbul"),
		"Europe/Jersey":                    Tr("Jersey (UTC+00) Jersey"),
		"Europe/Kaliningrad":               Tr("Russia (UTC+03) Kaliningrad"),
		"Europe/Kiev":                      Tr("Ukraine (UTC+02) Kiev"),
		"Europe/Lisbon":                    Tr("Portugal (UTC+00) Lisbon"),
		"Europe/Ljubljana":                 Tr("Slovenia (UTC+01) Ljubljana"),
		"Europe/London":                    Tr("UK (UTC+00) London"),
		"Europe/Luxembourg":                Tr("Luxembourg (UTC+01) Luxembourg"),
		"Europe/Madrid":                    Tr("Spain (UTC+01) Madrid"),
		"Europe/Malta":                     Tr("Malta (UTC+01) Malta"),
		"Europe/Mariehamn":                 Tr("Aland Islands (UTC+02) Mariehamn"),
		"Europe/Minsk":                     Tr("Belarus (UTC+03) Minsk"),
		"Europe/Monaco":                    Tr("Monaco (UTC+01) Monaco"),
		"Europe/Moscow":                    Tr("Russia (UTC+04) Moscow"),
		"Europe/Nicosia":                   Tr("Italy (UTC+02) Nicosia"),
		"Europe/Oslo":                      Tr("Norway (UTC+01) Oslo"),
		"Europe/Paris":                     Tr("France (UTC+01) Paris"),
		"Europe/Podgorica":                 Tr("Montenegro (UTC+01) Podgorica"),
		"Europe/Prague":                    Tr("Czech Republic (UTC+01) Prague"),
		"Europe/Riga":                      Tr("Latvia (UTC+02) Riga"),
		"Europe/Rome":                      Tr("Italy (UTC+01) Rome"),
		"Europe/Samara":                    Tr("Russia (UTC+04) Samara"),
		"Europe/San_Marino":                Tr("San Marino (UTC+01) San Marino"),
		"Europe/Sarajevo":                  Tr("Bosnia and Herzegovina (UTC+01) Sarajevo"),
		"Europe/Simferopol":                Tr("Ukraine (UTC+02) Simferopol"),
		"Europe/Skopje":                    Tr("Macedonia (FYROM) (UTC+01) Skopje"),
		"Europe/Sofia":                     Tr("Bulgaria (UTC+02) Sofia"),
		"Europe/Stockholm":                 Tr("Sweden (UTC+01) Stockholm"),
		"Europe/Tallinn":                   Tr("Estonia (UTC+02) Tallinn"),
		"Europe/Tirane":                    Tr("Albania (UTC+01) Tirane"),
		"Europe/Tiraspol":                  Tr("Moldova (UTC+02) Tiraspol"),
		"Europe/Uzhgorod":                  Tr("Ukraine (UTC+02) Uzhgorod"),
		"Europe/Vaduz":                     Tr("Liechtenstein (UTC+01) Vaduz"),
		"Europe/Vatican":                   Tr("Vatican City (UTC+01) Vatican"),
		"Europe/Vienna":                    Tr("Austria (UTC+01) Vienna"),
		"Europe/Vilnius":                   Tr("Lithuania (UTC+02) Vilnius"),
		"Europe/Volgograd":                 Tr("Russia (UTC+04) Volgograd"),
		"Europe/Warsaw":                    Tr("Poland (UTC+01) Warsaw"),
		"Europe/Zagreb":                    Tr("Croatia (UTC+01) Zagreb"),
		"Europe/Zaporozhye":                Tr("Ukraine (UTC+02) Zaporozhye"),
		"Europe/Zurich":                    Tr("Switzerland (UTC+01) Zurich"),
		"GB":                               Tr("United Kingdom (UTC+00) GB"),
		"GB-Eire":                          Tr("Ireland (UTC+00) GB Eire"),
		"GMT":                              Tr("USA (UTC+00) GMT"),
		"GMT+0":                            Tr("Brazil (UTC+00) GMT"),
		"Greenwich":                        Tr("UK (UTC+00) Greenwich"),
		"Hongkong":                         Tr("Hong Kong (UTC+08) Hongkong"),
		"HST":                              Tr("Indonesia (UTC-10) HST"),
		"Iceland":                          Tr("Iceland (UTC+00) Iceland"),
		"Indian/Antananarivo":              Tr("Madagascar (UTC+03) Antananarivo"),
		"Indian/Chagos":                    Tr("British Indian Ocean Territory (UTC+06) Chagos"),
		"Indian/Christmas":                 Tr("Christmas Island (UTC+07) Christmas"),
		"Indian/Kerguelen":                 Tr("Grande Terre (UTC+05) Kerguelen"),
		"Indian/Mahe":                      Tr("Seychelles (UTC+04) Mahe"),
		"Indian/Maldives":                  Tr("Maldives (UTC+05) Maldives"),
		"Indian/Mauritius":                 Tr("India (UTC+04) Mauritius"),
		"Indian/Reunion":                   Tr("USA (UTC+04) Reunion"),
		"Iran":                             Tr("Iran (UTC+02) Iran"),
		"Jamaica":                          Tr("Jamaica (UTC-05) Jamaica"),
		"Japan":                            Tr("Japan (UTC+09) Japan"),
		"Kwajalein":                        Tr("RMI (UTC+12) Kwajalein"),
		"Libya":                            Tr("Libya (UTC+02) Libya"),
		"MET":                              Tr("France (UTC+01) MET"),
		"Mexico/BajaNorte":                 Tr("Mexico (UTC-08) BajaNorte"),
		"Mexico/BajaSur":                   Tr("Mexico (UTC-07) BajaSur"),
		"Mexico/General":                   Tr("Mexico (UTC-06) General"),
		"MST":                              Tr("The Netherlands (UTC-07) MST"),
		"Navajo":                           Tr("USA (UTC-07) Navajo"),
		"NZ":                               Tr("New Zealand (UTC+12) NZ"),
		"Pacific/Auckland":                 Tr("New Zealand (UTC+12) Auckland"),
		"Pacific/Chatham":                  Tr("USA (UTC+10) Chatham"),
		"Pacific/Easter":                   Tr("USA (UTC-06) Easter"),
		"Pacific/Efate":                    Tr("Vanuatu (UTC+11) Efate"),
		"Pacific/Enderbury":                Tr("Australia (UTC+13) Enderbury"),
		"Pacific/Fakaofo":                  Tr("Tokelau (UTC+13) Fakaofo"),
		"Pacific/Fiji":                     Tr("Fiji (UTC+12) Fiji"),
		"Pacific/Funafuti":                 Tr("Tuvalu (UTC+12) Funafuti"),
		"Pacific/Galapagos":                Tr("Australia (UTC-06) Galapagos"),
		"Pacific/Gambier":                  Tr("Australia (UTC-09) Gambier"),
		"Pacific/Guadalcanal":              Tr("Solomon Islands (UTC+11) Guadalcanal"),
		"Pacific/Guam":                     Tr("Guam (UTC+10) Guam"),
		"Pacific/Honolulu":                 Tr("Hawaii 96813 (UTC-10) Honolulu"),
		"Pacific/Johnston":                 Tr("USA (UTC-10) Johnston"),
		"Pacific/Kosrae":                   Tr("Australia (UTC+11) Kosrae"),
		"Pacific/Kwajalein":                Tr("RMI (UTC+12) Kwajalein"),
		"Pacific/Marquesas":                Tr("French Polynesia (UTC-11) Marquesas"),
		"Pacific/Nauru":                    Tr("Australia (UTC+12) Nauru"),
		"Pacific/Niue":                     Tr("Niue (UTC-11) Niue"),
		"Pacific/Norfolk":                  Tr("USA (UTC+11) Norfolk"),
		"Pacific/Palau":                    Tr("Australia (UTC+09) Palau"),
		"Pacific/Pitcairn":                 Tr("Australia (UTC-08) Pitcairn"),
		"Pacific/Pohnpei":                  Tr("Micronesia (UTC+11) Pohnpei"),
		"Pacific/Ponape":                   Tr("Micronesia (UTC+11) Ponape"),
		"Pacific/Port_Moresby":             Tr("Papua New Guinea (UTC+10) Port Moresby"),
		"Pacific/Rarotonga":                Tr("Australia (UTC-10) Rarotonga"),
		"Pacific/Saipan":                   Tr("CNMI (UTC+10) Saipan"),
		"Pacific/Samoa":                    Tr("USA (UTC-11) Samoa"),
		"Pacific/Tahiti":                   Tr("French Polynesia (UTC-10) Tahiti"),
		"Pacific/Tarawa":                   Tr("Kiribati (UTC+12) Tarawa"),
		"Pacific/Tongatapu":                Tr("Tonga (UTC+13) Tongatapu"),
		"Pacific/Truk":                     Tr("USA (UTC+10) Truk"),
		"Pacific/Wake":                     Tr("USA (UTC+12) Wake"),
		"Pacific/Wallis":                   Tr("Australia (UTC+12) Wallis"),
		"Poland":                           Tr("Poland (UTC+01) Poland"),
		"Portugal":                         Tr("Portugal (UTC+00) Portugal"),
		"PRC":                              Tr("USA (UTC+08) PRC"),
		"ROK":                              Tr("Czech Republic (UTC+09) ROK"),
		"Turkey":                           Tr("Turkey (UTC+02) Turkey"),
		"UCT":                              Tr("South Africa (UTC+00) UCT"),
		"Universal":                        Tr("USA (UTC+00) Universal"),
		"US/Alaska":                        Tr("USA (UTC-09) Alaska"),
		"US/Aleutian":                      Tr("USA (UTC-10) Aleutian"),
		"US/Arizona":                       Tr("USA (UTC-07) Arizona"),
		"US/Central":                       Tr("USA (UTC-06) Central"),
		"US/Eastern":                       Tr("USA (UTC-05) Eastern"),
		"US/East-Indiana":                  Tr("USA (UTC-05) East Indiana"),
		"US/Hawaii":                        Tr("USA (UTC-10) Hawaii"),
		"US/Indiana-Starke":                Tr("USA (UTC-06) Indiana Starke"),
		"US/Michigan":                      Tr("USA (UTC-05) Michigan"),
		"US/Mountain":                      Tr("USA (UTC-07) Mountain"),
		"US/Pacific":                       Tr("USA (UTC-08) Pacific"),
		"US/Pacific-New":                   Tr("USA (UTC-08) Pacific New"),
		"US/Samoa":                         Tr("USA (UTC-11) Samoa"),
		"UTC":                              Tr("USA (UTC+00) UTC"),
		"WET":                              Tr("USA (UTC+00) WET"),
		"W-SU":                             Tr("WA (UTC+04) W SU"),
		"Zulu":                             Tr("USA (UTC+00) Zulu"),
	}
}
