package datetime

import "path"
import dutils "pkg.linuxdeepin.com/lib/utils"
import . "pkg.linuxdeepin.com/lib/gettext"

type zoneCityInfo struct {
	Zone string
	Desc string
}

var zoneInfos []zoneCityInfo

func checkZoneValid(offset, zone, desc string) {
	if !dutils.IsFileExist(path.Join("/usr/share/zoneinfo", zone)) {
		return
	}

	info := zoneCityInfo{zone, "UTC" + offset + " " + desc}
	zoneInfos = append(zoneInfos, info)
}

func initZoneInfos() {
	checkZoneValid("-11:00", "Pacific/Midway", Tr("Midway"))
	checkZoneValid("-11:00", "Pacific/Niue", Tr("Niue"))
	checkZoneValid("-11:00", "Pacific/Pago_Pago", Tr("Pago Pago"))
	//checkZoneValid("-11:00", "Pacific/Samoa", Tr("Pacific/Samoa"))
	//checkZoneValid("-11:00", "US/Samoa", Tr("US/Samoa"))

	checkZoneValid("-10:00", "America/Adak", Tr("Adak"))
	checkZoneValid("-10:00", "America/Atka", Tr("Atka"))
	checkZoneValid("-10:00", "Pacific/Honolulu", Tr("Honolulu"))
	checkZoneValid("-10:00", "Pacific/Johnston", Tr("Johnston"))
	checkZoneValid("-10:00", "Pacific/Rarotonga", Tr("Rarotonga"))
	checkZoneValid("-10:00", "Pacific/Tahiti", Tr("Tahiti"))
	checkZoneValid("-10:00", "US/Aleutian", Tr("Aleutian"))
	checkZoneValid("-10:00", "US/Hawaii", Tr("Hawaii"))

	checkZoneValid("-09:30", "Pacific/Marquesas", Tr("Marquesas"))

	checkZoneValid("-09:00", "America/Anchorage", Tr("Anchorage"))
	checkZoneValid("-09:00", "America/Juneau", Tr("Juneau"))
	checkZoneValid("-09:00", "America/Nome", Tr("Nome"))
	checkZoneValid("-09:00", "America/Sitka", Tr("Sitka"))
	checkZoneValid("-09:00", "America/Yakutat", Tr("Yakutat"))
	checkZoneValid("-09:00", "Pacific/Gambier", Tr("Gambier"))
	checkZoneValid("-09:00", "US/Alaska", Tr("Alaska"))

	checkZoneValid("-08:00", "America/Dawson", Tr("Dawson"))
	checkZoneValid("-08:00", "America/Ensenada", Tr("Ensenada"))
	checkZoneValid("-08:00", "America/Los_Angeles", Tr("Los Angeles"))
	checkZoneValid("-08:00", "America/Metlakatla", Tr("Metlakatla"))
	checkZoneValid("-08:00", "America/Santa_Isabel", Tr("Santa Isabel"))
	checkZoneValid("-08:00", "America/Tijuana", Tr("Tijuana"))
	checkZoneValid("-08:00", "America/Vancouver", Tr("Vancouver"))
	checkZoneValid("-08:00", "America/Whitehorse", Tr("Whitehorse"))
	//checkZoneValid("-08:00", "Canada/Pacific", Tr("Canada/Pacific"))
	checkZoneValid("-08:00", "Canada/Yukon", Tr("Yukon"))
	checkZoneValid("-08:00", "Mexico/BajaNorte", Tr("BajaNorte"))
	checkZoneValid("-08:00", "Pacific/Pitcairn", Tr("Pitcairn"))
	//checkZoneValid("-08:00", "US/Pacific", Tr("US/Pacific"))

	checkZoneValid("-07:00", "America/Boise", Tr("Boise"))
	checkZoneValid("-07:00", "America/Cambridge_Bay", Tr("Cambridge Bay"))
	checkZoneValid("-07:00", "America/Chihuahua", Tr("Chihuahua"))
	checkZoneValid("-07:00", "America/Creston", Tr("Creston"))
	checkZoneValid("-07:00", "America/Dawson_Creek", Tr("Dawson Creek"))
	checkZoneValid("-07:00", "America/Denver", Tr("Denver"))
	checkZoneValid("-07:00", "America/Edmonton", Tr("Edmonton"))
	checkZoneValid("-07:00", "America/Hermosillo", Tr("Hermosillo"))
	checkZoneValid("-07:00", "America/Inuvik", Tr("Inuvik"))
	checkZoneValid("-07:00", "America/Mazatlan", Tr("Mazatlan"))
	checkZoneValid("-07:00", "America/Ojinaga", Tr("Ojinaga"))
	checkZoneValid("-07:00", "America/Phoenix", Tr("Phoenix"))
	checkZoneValid("-07:00", "America/Shiprock", Tr("Shiprock"))
	checkZoneValid("-07:00", "America/Yellowknife", Tr("Yellowknife"))

	checkZoneValid("-07:00", "Canada/Mountain", Tr("Canada/Mountain"))
	checkZoneValid("-07:00", "Mexico/BajaSur", Tr("BajaSur"))
	checkZoneValid("-07:00", "Navajo", Tr("Navajo"))
	checkZoneValid("-07:00", "US/Arizona", Tr("Arizona"))
	checkZoneValid("-07:00", "US/Mountain", Tr("US/Mountain"))

	checkZoneValid("-06:00", "America/Bahia_Banderas", Tr("Bahia Banderas"))
	checkZoneValid("-06:00", "America/Belize", Tr("Belize"))
	checkZoneValid("-06:00", "America/Cancun", Tr("Cancun"))
	checkZoneValid("-06:00", "America/Chicago", Tr("Chicago"))
	checkZoneValid("-06:00", "America/Costa_Rica", Tr("Costa Rica"))
	checkZoneValid("-06:00", "America/El_Salvador", Tr("El Salvador"))
	checkZoneValid("-06:00", "America/Guatemala", Tr("Guatemala"))

	//checkZoneValid("-06:00", "America/Indiana/Knox", Tr("Indiana/Knox"))
	checkZoneValid("-06:00", "America/Indiana/Tell_City", Tr("Tell City"))
	checkZoneValid("-06:00", "America/Indiana/Valparaiso", Tr("Valparaiso"))

	checkZoneValid("-06:00", "America/Knox_IN", Tr("Knox IN"))
	checkZoneValid("-06:00", "America/Managua", Tr("Managua"))
	checkZoneValid("-06:00", "America/Matamoros", Tr("Matamoros"))
	checkZoneValid("-06:00", "America/Menominee", Tr("Menominee"))
	checkZoneValid("-06:00", "America/Merida", Tr("Merida"))
	checkZoneValid("-06:00", "America/Mexico_City", Tr("Mexico City"))
	checkZoneValid("-06:00", "America/Monterrey", Tr("Monterrey"))
	checkZoneValid("-06:00", "America/North_Dakota/Beulah", Tr("Beulah"))
	checkZoneValid("-06:00", "America/North_Dakota/Center", Tr("North Dakota/Center"))
	checkZoneValid("-06:00", "America/North_Dakota/New_Salem", Tr("North Dakota/New Salem"))
	checkZoneValid("-06:00", "America/Rainy_River", Tr("Rainy River"))
	checkZoneValid("-06:00", "America/Rankin_Inlet", Tr("Rankin Inlet"))
	checkZoneValid("-06:00", "America/Regina", Tr("Regina"))
	checkZoneValid("-06:00", "America/Resolute", Tr("Resolute"))
	checkZoneValid("-06:00", "America/Swift_Current", Tr("Swift Current"))
	checkZoneValid("-06:00", "America/Tegucigalpa", Tr("Tegucigalpa"))
	checkZoneValid("-06:00", "America/Winnipeg", Tr("Winnipeg"))
	//checkZoneValid("-06:00", "Canada/Central", Tr("Canada/Central"))
	checkZoneValid("-06:00", "Canada/East-Saskatchewan", Tr("East-Saskatchewan"))
	checkZoneValid("-06:00", "Canada/Saskatchewan", Tr("Saskatchewan"))
	//checkZoneValid("-06:00", "Chile/EasterIsland", Tr("EasterIsland"))
	checkZoneValid("-06:00", "Mexico/General", Tr("General"))
	checkZoneValid("-06:00", "Pacific/Easter", Tr("Easter Island"))
	checkZoneValid("-06:00", "Pacific/Galapagos", Tr("Galapagos"))
	//checkZoneValid("-06:00", "US/Central", Tr("US/Central"))
	checkZoneValid("-06:00", "US/Indiana-Starke", Tr("Indiana-Starke"))

	checkZoneValid("-05:00", "America/Atikokan", Tr("Atikokan"))
	checkZoneValid("-05:00", "America/Bogota", Tr("Bogota"))
	checkZoneValid("-05:00", "America/Cayman", Tr("Cayman"))
	checkZoneValid("-05:00", "America/Coral_Harbour", Tr("Coral Harbour"))
	checkZoneValid("-05:00", "America/Detroit", Tr("Detroit"))
	checkZoneValid("-05:00", "America/Eirunepe", Tr("Eirunepe"))
	checkZoneValid("-05:00", "America/Fort_Wayne", Tr("Fort Wayne"))
	checkZoneValid("-05:00", "America/Grand_Turk", Tr("Grand Turk"))
	checkZoneValid("-05:00", "America/Guayaquil", Tr("Guayaquil"))
	checkZoneValid("-05:00", "America/Havana", Tr("Havana"))
	//checkZoneValid("-05:00", "America/Indiana/Indianapolis", Tr("Indiana/Indianapolis"))
	checkZoneValid("-05:00", "America/Indiana/Marengo", Tr("Marengo"))
	checkZoneValid("-05:00", "America/Indiana/Petersburg", Tr("Petersburg"))
	checkZoneValid("-05:00", "America/Indiana/Vevay", Tr("Vevay"))
	checkZoneValid("-05:00", "America/Indiana/Vincennes", Tr("Vincennes"))
	checkZoneValid("-05:00", "America/Indiana/Winamac", Tr("Winamac"))
	checkZoneValid("-05:00", "America/Indianapolis", Tr("Indianapolis"))
	checkZoneValid("-05:00", "America/Iqaluit", Tr("Iqaluit"))
	checkZoneValid("-05:00", "America/Jamaica", Tr("Jamaica"))
	//checkZoneValid("-05:00", "America/Kentucky/Louisville", Tr("Kentucky/Louisville"))
	checkZoneValid("-05:00", "America/Kentucky/Monticello", Tr("Monticello"))
	checkZoneValid("-05:00", "America/Lima", Tr("Lima"))
	checkZoneValid("-05:00", "America/Louisville", Tr("Louisville"))
	checkZoneValid("-05:00", "America/Montreal", Tr("Montreal"))
	checkZoneValid("-05:00", "America/Nassau", Tr("Nassau"))
	checkZoneValid("-05:00", "America/New_York", Tr("New York"))
	checkZoneValid("-05:00", "America/Nipigon", Tr("Nipigon"))
	checkZoneValid("-05:00", "America/Panama", Tr("Panama"))
	checkZoneValid("-05:00", "America/Pangnirtung", Tr("Pangnirtung"))
	checkZoneValid("-05:00", "America/Port-au-Prince", Tr("Port-au-Prince"))
	checkZoneValid("-05:00", "America/Porto_Acre", Tr("Porto Acre"))
	checkZoneValid("-05:00", "America/Rio_Branco", Tr("Rio Branco"))
	checkZoneValid("-05:00", "America/Thunder_Bay", Tr("Thunder Bay"))
	checkZoneValid("-05:00", "America/Toronto", Tr("Toronto"))
	checkZoneValid("-05:00", "Brazil/Acre", Tr("Acre"))
	checkZoneValid("-05:00", "Canada/Eastern", Tr("Canada/Eastern"))
	checkZoneValid("-05:00", "Cuba", Tr("Cuba"))
	//checkZoneValid("-05:00", "Jamaica", Tr("Jamaica"))
	checkZoneValid("-05:00", "US/Eastern", Tr("US/Eastern"))
	checkZoneValid("-05:00", "US/East-Indiana", Tr("East-Indiana"))
	checkZoneValid("-05:00", "US/Michigan", Tr("Michigan"))

	checkZoneValid("-04:30", "America/Caracas", Tr("Caracas"))

	checkZoneValid("-04:00", "America/Anguilla", Tr("Anguilla"))
	checkZoneValid("-04:00", "America/Antigua", Tr("Antigua"))
	checkZoneValid("-04:00", "America/Aruba", Tr("Aruba"))
	checkZoneValid("-04:00", "America/Asuncion", Tr("Asuncion"))
	checkZoneValid("-04:00", "America/Barbados", Tr("Barbados"))
	checkZoneValid("-04:00", "America/Blanc-Sablon", Tr("Blanc-Sablon"))
	checkZoneValid("-04:00", "America/Boa_Vista", Tr("Boa Vista"))
	checkZoneValid("-04:00", "America/Campo_Grande", Tr("Campo Grande"))
	checkZoneValid("-04:00", "America/Cuiaba", Tr("Cuiaba"))
	checkZoneValid("-04:00", "America/Curacao", Tr("Curacao"))
	checkZoneValid("-04:00", "America/Dominica", Tr("Dominica"))
	checkZoneValid("-04:00", "America/Glace_Bay", Tr("Glace Bay"))
	checkZoneValid("-04:00", "America/Goose_Bay", Tr("Goose Bay"))
	checkZoneValid("-04:00", "America/Grenada", Tr("Grenada"))
	checkZoneValid("-04:00", "America/Guadeloupe", Tr("Guadeloupe"))
	checkZoneValid("-04:00", "America/Guyana", Tr("Guyana"))
	checkZoneValid("-04:00", "America/Halifax", Tr("Halifax"))
	checkZoneValid("-04:00", "America/Kralendijk", Tr("Kralendijk"))
	checkZoneValid("-04:00", "America/La_Paz", Tr("La Paz"))
	checkZoneValid("-04:00", "America/Lower_Princes", Tr("Lower Princes"))
	checkZoneValid("-04:00", "America/Manaus", Tr("Manaus"))
	checkZoneValid("-04:00", "America/Marigot", Tr("Marigot"))
	checkZoneValid("-04:00", "America/Martinique", Tr("Martinique"))
	checkZoneValid("-04:00", "America/Moncton", Tr("Moncton"))
	checkZoneValid("-04:00", "America/Montserrat", Tr("Montserrat"))
	checkZoneValid("-04:00", "America/Port_of_Spain", Tr("Port of Spain"))
	checkZoneValid("-04:00", "America/Porto_Velho", Tr("Porto Velho"))
	checkZoneValid("-04:00", "America/Puerto_Rico", Tr("Puerto Rico"))
	checkZoneValid("-04:00", "America/Santiago", Tr("Santiago"))
	checkZoneValid("-04:00", "America/Santo_Domingo", Tr("Santo Domingo"))
	checkZoneValid("-04:00", "America/St_Barthelemy", Tr("St Barthelemy"))
	checkZoneValid("-04:00", "America/St_Kitts", Tr("St Kitts"))
	checkZoneValid("-04:00", "America/St_Lucia", Tr("St Lucia"))
	checkZoneValid("-04:00", "America/St_Thomas", Tr("St Thomas"))
	checkZoneValid("-04:00", "America/St_Vincent", Tr("St Vincent"))
	checkZoneValid("-04:00", "America/Thule", Tr("Thule"))
	checkZoneValid("-04:00", "America/Tortola", Tr("Tortola"))
	checkZoneValid("-04:00", "America/Virgin", Tr("Virgin"))
	checkZoneValid("-04:00", "Antarctica/Palmer", Tr("Palmer"))
	checkZoneValid("-04:00", "Atlantic/Bermuda", Tr("Bermuda"))
	checkZoneValid("-04:00", "Brazil/West", Tr("Brazil/West"))
	checkZoneValid("-04:00", "Canada/Atlantic", Tr("Atlantic"))
	checkZoneValid("-04:00", "Chile/Continental", Tr("Continental"))

	checkZoneValid("-03:30", "America/St_Johns", Tr("St Johns"))
	checkZoneValid("-03:30", "Canada/Newfoundland", Tr("Newfoundland"))

	checkZoneValid("-03:00", "America/Araguaina", Tr("Araguaina"))
	//checkZoneValid("-03:00", "America/Argentina/Buenos_Aires", Tr("Argentina/Buenos Aires"))
	//checkZoneValid("-03:00", "America/Argentina/Catamarca", Tr("Argentina/Catamarca"))
	checkZoneValid("-03:00", "America/Argentina/ComodRivadavia", Tr("ComodRivadavia"))
	//checkZoneValid("-03:00", "America/Argentina/Cordoba", Tr("Argentina/Cordoba"))
	//checkZoneValid("-03:00", "America/Argentina/Jujuy", Tr("Argentina/Jujuy"))
	checkZoneValid("-03:00", "America/Argentina/La_Rioja", Tr("La Rioja"))
	//checkZoneValid("-03:00", "America/Argentina/Mendoza", Tr("Argentina/Mendoza"))
	checkZoneValid("-03:00", "America/Argentina/Rio_Gallegos", Tr("Rio Gallegos"))
	checkZoneValid("-03:00", "America/Argentina/Salta", Tr("Salta"))
	checkZoneValid("-03:00", "America/Argentina/San_Juan", Tr("San Juan"))
	checkZoneValid("-03:00", "America/Argentina/San_Luis", Tr("San Luis"))
	checkZoneValid("-03:00", "America/Argentina/Tucuman", Tr("Tucuman"))
	checkZoneValid("-03:00", "America/Argentina/Ushuaia", Tr("Ushuaia"))
	checkZoneValid("-03:00", "America/Bahia", Tr("Bahia"))
	checkZoneValid("-03:00", "America/Belem", Tr("Belem"))
	checkZoneValid("-03:00", "America/Buenos_Aires", Tr("Buenos Aires"))
	checkZoneValid("-03:00", "America/Catamarca", Tr("Catamarca"))
	checkZoneValid("-03:00", "America/Cayenne", Tr("Cayenne"))
	checkZoneValid("-03:00", "America/Cordoba", Tr("Cordoba"))
	checkZoneValid("-03:00", "America/Fortaleza", Tr("Fortaleza"))
	checkZoneValid("-03:00", "America/Godthab", Tr("Godthab"))
	checkZoneValid("-03:00", "America/Jujuy", Tr("Jujuy"))
	checkZoneValid("-03:00", "America/Maceio", Tr("Maceio"))
	checkZoneValid("-03:00", "America/Mendoza", Tr("Mendoza"))
	checkZoneValid("-03:00", "America/Miquelon", Tr("Miquelon"))
	checkZoneValid("-03:00", "America/Montevideo", Tr("Montevideo"))
	checkZoneValid("-03:00", "America/Paramaribo", Tr("Paramaribo"))
	checkZoneValid("-03:00", "America/Recife", Tr("Recife"))
	checkZoneValid("-03:00", "America/Rosario", Tr("Rosario"))
	checkZoneValid("-03:00", "America/Santarem", Tr("Santarem"))
	checkZoneValid("-03:00", "America/Sao_Paulo", Tr("Sao Paulo"))
	checkZoneValid("-03:00", "Antarctica/Rothera", Tr("Rothera"))
	checkZoneValid("-03:00", "Atlantic/Stanley", Tr("Stanley"))
	checkZoneValid("-03:00", "Brazil/East", Tr("Brazil East"))

	//checkZoneValid("-02:00", "America/Noronha", Tr("Americaoronha"))
	checkZoneValid("-02:00", "Atlantic/South_Georgia", Tr("South Georgia"))
	checkZoneValid("-02:00", "Brazil/DeNoronha", Tr("DeNoronha"))

	checkZoneValid("-01:00", "America/Scoresbysund", Tr("Scoresbysund"))
	checkZoneValid("-01:00", "Atlantic/Azores", Tr("Azores"))
	checkZoneValid("-01:00", "Atlantic/Cape_Verde", Tr("Cape Verde"))

	checkZoneValid("+00:00", "Africa/Abidjan", Tr("Abidjan"))
	checkZoneValid("+00:00", "Africa/Accra", Tr("Accra"))
	checkZoneValid("+00:00", "Africa/Bamako", Tr("Bamako"))
	checkZoneValid("+00:00", "Africa/Banjul", Tr("Banjul"))
	checkZoneValid("+00:00", "Africa/Bissau", Tr("Bissau"))
	checkZoneValid("+00:00", "Africa/Casablanca", Tr("Casablanca"))
	checkZoneValid("+00:00", "Africa/Conakry", Tr("Conakry"))
	checkZoneValid("+00:00", "Africa/Dakar", Tr("Dakar"))
	checkZoneValid("+00:00", "Africa/El_Aaiun", Tr("El Aaiun"))
	checkZoneValid("+00:00", "Africa/Freetown", Tr("Freetown"))
	checkZoneValid("+00:00", "Africa/Lome", Tr("Lome"))
	checkZoneValid("+00:00", "Africa/Monrovia", Tr("Monrovia"))
	checkZoneValid("+00:00", "Africa/Nouakchott", Tr("Nouakchott"))
	checkZoneValid("+00:00", "Africa/Ouagadougou", Tr("Ouagadougou"))
	checkZoneValid("+00:00", "Africa/Sao_Tome", Tr("Sao Tome"))
	checkZoneValid("+00:00", "Africa/Timbuktu", Tr("Timbuktu"))
	checkZoneValid("+00:00", "America/Danmarkshavn", Tr("Danmarkshavn"))
	checkZoneValid("+00:00", "Antarctica/Troll", Tr("Troll"))
	checkZoneValid("+00:00", "Atlantic/Canary", Tr("Canary"))
	//checkZoneValid("+00:00", "Atlantic/Faeroe", Tr("Faeroe"))
	checkZoneValid("+00:00", "Atlantic/Faroe", Tr("Faroe"))
	checkZoneValid("+00:00", "Atlantic/Madeira", Tr("Madeira"))
	checkZoneValid("+00:00", "Atlantic/Reykjavik", Tr("Reykjavik"))
	checkZoneValid("+00:00", "Atlantic/St_Helena", Tr("St Helena"))
	checkZoneValid("+00:00", "Eire", Tr("Eire"))
	//checkZoneValid("+00:00", "Etc/GMT", Tr("GMT"))
	//checkZoneValid("+00:00", "Etc/GMT+0", Tr("GMT+0"))
	//checkZoneValid("+00:00", "Etc/UCT", Tr("UCT"))
	//checkZoneValid("+00:00", "Etc/Universal", Tr("Universal"))
	//checkZoneValid("+00:00", "Etc/UTC", Tr("UTC"))
	//checkZoneValid("+00:00", "Etc/Zulu", Tr("Zulu"))
	checkZoneValid("+00:00", "Europe/Belfast", Tr("Belfast"))
	checkZoneValid("+00:00", "Europe/Dublin", Tr("Dublin"))
	checkZoneValid("+00:00", "Europe/Guernsey", Tr("Guernsey"))
	checkZoneValid("+00:00", "Europe/Isle_of_Man", Tr("Isle of Man"))
	checkZoneValid("+00:00", "Europe/Jersey", Tr("Jersey"))
	checkZoneValid("+00:00", "Europe/Lisbon", Tr("Lisbon"))
	checkZoneValid("+00:00", "GB", Tr("GB"))
	checkZoneValid("+00:00", "GB-Eire", Tr("GB-Eire"))
	checkZoneValid("+00:00", "GMT", Tr("GMT"))
	//checkZoneValid("+00:00", "GMT+0", Tr("GMT+0"))
	//checkZoneValid("+00:00", "GMT0", Tr("GMT0"))
	//checkZoneValid("+00:00", "GMT-0", Tr("GMT-0"))
	checkZoneValid("+00:00", "Greenwich", Tr("Greenwich"))
	checkZoneValid("+00:00", "Iceland", Tr("Iceland"))
	checkZoneValid("+00:00", "Portugal", Tr("Portugal"))
	checkZoneValid("+00:00", "UCT", Tr("UCT"))
	checkZoneValid("+00:00", "Universal", Tr("Universal"))
	checkZoneValid("+00:00", "UTC", Tr("UTC"))
	checkZoneValid("+00:00", "Zulu", Tr("Zulu"))

	checkZoneValid("+01:00", "Africa/Algiers", Tr("Algiers"))
	checkZoneValid("+01:00", "Africa/Bangui", Tr("Bangui"))
	checkZoneValid("+01:00", "Africa/Brazzaville", Tr("Brazzaville"))
	checkZoneValid("+01:00", "Africa/Ceuta", Tr("Ceuta"))
	checkZoneValid("+01:00", "Africa/Douala", Tr("Douala"))
	checkZoneValid("+01:00", "Africa/Kinshasa", Tr("Kinshasa"))
	checkZoneValid("+01:00", "Africa/Lagos", Tr("Lagos"))
	checkZoneValid("+01:00", "Africa/Libreville", Tr("Libreville"))
	checkZoneValid("+01:00", "Africa/Luanda", Tr("Luanda"))
	checkZoneValid("+01:00", "Africa/Malabo", Tr("Malabo"))
	checkZoneValid("+01:00", "Africa/Ndjamena", Tr("Ndjamena"))
	checkZoneValid("+01:00", "Africa/Niamey", Tr("Niamey"))
	checkZoneValid("+01:00", "Africa/Porto-Novo", Tr("Porto-Novo"))
	checkZoneValid("+01:00", "Africa/Tunis", Tr("Tunis"))
	checkZoneValid("+01:00", "Africa/Windhoek", Tr("Windhoek"))
	checkZoneValid("+01:00", "Arctic/Longyearbyen", Tr("Longyearbyen"))
	checkZoneValid("+01:00", "Atlantic/Jan_Mayen", Tr("Jan Mayen"))
	checkZoneValid("+01:00", "Europe/Amsterdam", Tr("Amsterdam"))
	checkZoneValid("+01:00", "Europe/Andorra", Tr("Andorra"))
	checkZoneValid("+01:00", "Europe/Belgrade", Tr("Belgrade"))
	checkZoneValid("+01:00", "Europe/Berlin", Tr("Berlin"))
	checkZoneValid("+01:00", "Europe/Bratislava", Tr("Bratislava"))
	checkZoneValid("+01:00", "Europe/Brussels", Tr("Brussels"))
	checkZoneValid("+01:00", "Europe/Budapest", Tr("Budapest"))
	checkZoneValid("+01:00", "Europe/Busingen", Tr("Busingen"))
	checkZoneValid("+01:00", "Europe/Copenhagen", Tr("Copenhagen"))
	checkZoneValid("+01:00", "Europe/Gibraltar", Tr("Gibraltar"))
	checkZoneValid("+01:00", "Europe/Ljubljana", Tr("Ljubljana"))
	checkZoneValid("+01:00", "Europe/Luxembourg", Tr("Luxembourg"))
	checkZoneValid("+01:00", "Europe/Madrid", Tr("Madrid"))
	checkZoneValid("+01:00", "Europe/Malta", Tr("Malta"))
	checkZoneValid("+01:00", "Europe/Monaco", Tr("Monaco"))
	checkZoneValid("+01:00", "Europe/Oslo", Tr("Oslo"))
	checkZoneValid("+01:00", "Europe/Paris", Tr("Paris"))
	checkZoneValid("+01:00", "Europe/Podgorica", Tr("Podgorica"))
	checkZoneValid("+01:00", "Europe/Prague", Tr("Prague"))
	checkZoneValid("+01:00", "Europe/Rome", Tr("Rome"))
	checkZoneValid("+01:00", "Europe/San_Marino", Tr("San Marino"))
	checkZoneValid("+01:00", "Europe/Sarajevo", Tr("Sarajevo"))
	checkZoneValid("+01:00", "Europe/Skopje", Tr("Skopje"))
	checkZoneValid("+01:00", "Europe/Stockholm", Tr("Stockholm"))
	checkZoneValid("+01:00", "Europe/Tirane", Tr("Tirane"))
	checkZoneValid("+01:00", "Europe/Vaduz", Tr("Vaduz"))
	checkZoneValid("+01:00", "Europe/Vatican", Tr("Vatican"))
	checkZoneValid("+01:00", "Europe/Vienna", Tr("Vienna"))
	checkZoneValid("+01:00", "Europe/Warsaw", Tr("Warsaw"))
	checkZoneValid("+01:00", "Europe/Zagreb", Tr("Zagreb"))
	checkZoneValid("+01:00", "Europe/Zurich", Tr("Zurich"))
	checkZoneValid("+01:00", "Poland", Tr("Poland"))

	checkZoneValid("+02:00", "Africa/Blantyre", Tr("Blantyre"))
	checkZoneValid("+02:00", "Africa/Bujumbura", Tr("Bujumbura"))
	checkZoneValid("+02:00", "Africa/Cairo", Tr("Cairo"))
	checkZoneValid("+02:00", "Africa/Gaborone", Tr("Gaborone"))
	checkZoneValid("+02:00", "Africa/Harare", Tr("Harare"))
	checkZoneValid("+02:00", "Africa/Johannesburg", Tr("Johannesburg"))
	checkZoneValid("+02:00", "Africa/Kigali", Tr("Kigali"))
	checkZoneValid("+02:00", "Africa/Lubumbashi", Tr("Lubumbashi"))
	checkZoneValid("+02:00", "Africa/Lusaka", Tr("Lusaka"))
	checkZoneValid("+02:00", "Africa/Maputo", Tr("Maputo"))
	checkZoneValid("+02:00", "Africa/Maseru", Tr("Maseru"))
	checkZoneValid("+02:00", "Africa/Mbabane", Tr("Mbabane"))
	checkZoneValid("+02:00", "Africa/Tripoli", Tr("Tripoli"))
	checkZoneValid("+02:00", "Asia/Amman", Tr("Amman"))
	checkZoneValid("+02:00", "Asia/Beirut", Tr("Beirut"))
	checkZoneValid("+02:00", "Asia/Damascus", Tr("Damascus"))
	checkZoneValid("+02:00", "Asia/Gaza", Tr("Gaza"))
	checkZoneValid("+02:00", "Asia/Hebron", Tr("Hebron"))
	checkZoneValid("+02:00", "Asia/Istanbul", Tr("Istanbul"))
	checkZoneValid("+02:00", "Asia/Jerusalem", Tr("Jerusalem"))
	checkZoneValid("+02:00", "Asia/Nicosia", Tr("Nicosia"))
	checkZoneValid("+02:00", "Asia/Tel_Aviv", Tr("Tel Aviv"))
	checkZoneValid("+02:00", "Egypt", Tr("Egypt"))
	checkZoneValid("+02:00", "Europe/Athens", Tr("Athens"))
	checkZoneValid("+02:00", "Europe/Bucharest", Tr("Bucharest"))
	checkZoneValid("+02:00", "Europe/Chisinau", Tr("Chisinau"))
	checkZoneValid("+02:00", "Europe/Helsinki", Tr("Helsinki"))
	//checkZoneValid("+02:00", "Europe/Istanbul", Tr("Istanbul"))
	checkZoneValid("+02:00", "Europe/Kiev", Tr("Kiev"))
	checkZoneValid("+02:00", "Europe/Mariehamn", Tr("Mariehamn"))
	//checkZoneValid("+02:00", "Europe/Nicosia", Tr("Nicosia"))
	checkZoneValid("+02:00", "Europe/Riga", Tr("Riga"))
	checkZoneValid("+02:00", "Europe/Sofia", Tr("Sofia"))
	checkZoneValid("+02:00", "Europe/Tallinn", Tr("Tallinn"))
	checkZoneValid("+02:00", "Europe/Tiraspol", Tr("Tiraspol"))
	checkZoneValid("+02:00", "Europe/Uzhgorod", Tr("Uzhgorod"))
	checkZoneValid("+02:00", "Europe/Vilnius", Tr("Vilnius"))
	checkZoneValid("+02:00", "Europe/Zaporozhye", Tr("Zaporozhye"))
	checkZoneValid("+02:00", "Israel", Tr("Israel"))
	checkZoneValid("+02:00", "Libya", Tr("Libya"))
	checkZoneValid("+02:00", "Turkey", Tr("Turkey"))

	checkZoneValid("+03:00", "Africa/Addis_Ababa", Tr("Addis Ababa"))
	checkZoneValid("+03:00", "Africa/Asmara", Tr("Asmara"))
	//checkZoneValid("+03:00", "Africa/Asmera", Tr("Asmera"))
	checkZoneValid("+03:00", "Africa/Dar_es_Salaam", Tr("Dar es Salaam"))
	checkZoneValid("+03:00", "Africa/Djibouti", Tr("Djibouti"))
	checkZoneValid("+03:00", "Africa/Juba", Tr("Juba"))
	checkZoneValid("+03:00", "Africa/Kampala", Tr("Kampala"))
	checkZoneValid("+03:00", "Africa/Khartoum", Tr("Khartoum"))
	checkZoneValid("+03:00", "Africa/Mogadishu", Tr("Mogadishu"))
	checkZoneValid("+03:00", "Africa/Nairobi", Tr("Nairobi"))
	checkZoneValid("+03:00", "Antarctica/Syowa", Tr("Syowa"))
	checkZoneValid("+03:00", "Asia/Aden", Tr("Aden"))
	checkZoneValid("+03:00", "Asia/Baghdad", Tr("Baghdad"))
	checkZoneValid("+03:00", "Asia/Bahrain", Tr("Bahrain"))
	checkZoneValid("+03:00", "Asia/Kuwait", Tr("Kuwait"))
	checkZoneValid("+03:00", "Asia/Qatar", Tr("Qatar"))
	checkZoneValid("+03:00", "Asia/Riyadh", Tr("Riyadh"))
	checkZoneValid("+03:00", "Europe/Kaliningrad", Tr("Kaliningrad"))
	checkZoneValid("+03:00", "Europe/Minsk", Tr("Minsk"))
	checkZoneValid("+03:00", "Indian/Antananarivo", Tr("Antananarivo"))
	checkZoneValid("+03:00", "Indian/Comoro", Tr("Comoro"))
	checkZoneValid("+03:00", "Indian/Mayotte", Tr("Mayotte"))

	checkZoneValid("+03:30", "Asia/Tehran", Tr("Tehran"))
	checkZoneValid("+03:30", "Iran", Tr("Iran"))

	checkZoneValid("+04:00", "Asia/Baku", Tr("Baku"))
	checkZoneValid("+04:00", "Asia/Dubai", Tr("Dubai"))
	checkZoneValid("+04:00", "Asia/Muscat", Tr("Muscat"))
	checkZoneValid("+04:00", "Asia/Tbilisi", Tr("Tbilisi"))
	checkZoneValid("+04:00", "Asia/Yerevan", Tr("Yerevan"))
	checkZoneValid("+04:00", "Europe/Moscow", Tr("Moscow"))
	checkZoneValid("+04:00", "Europe/Samara", Tr("Samara"))
	checkZoneValid("+04:00", "Europe/Simferopol", Tr("Simferopol"))
	checkZoneValid("+04:00", "Europe/Volgograd", Tr("Volgograd"))
	checkZoneValid("+04:00", "Indian/Mahe", Tr("Mahe"))
	checkZoneValid("+04:00", "Indian/Mauritius", Tr("Mauritius"))
	checkZoneValid("+04:00", "Indian/Reunion", Tr("Reunion"))
	checkZoneValid("+04:00", "W-SU", Tr("W-SU"))

	checkZoneValid("+04:30", "Asia/Kabul", Tr("Kabul"))

	checkZoneValid("+14:00", "Pacific/Kiritimati", Tr("Kiritimati"))

	checkZoneValid("+05:00", "Antarctica/Davis", Tr("Davis"))
	checkZoneValid("+05:00", "Antarctica/Mawson", Tr("Mawson"))
	checkZoneValid("+05:00", "Asia/Aqtau", Tr("Aqtau"))
	checkZoneValid("+05:00", "Asia/Aqtobe", Tr("Aqtobe"))
	checkZoneValid("+05:00", "Asia/Ashgabat", Tr("Ashgabat"))
	//checkZoneValid("+05:00", "Asia/Ashkhabad", Tr("Ashkhabad"))
	checkZoneValid("+05:00", "Asia/Dushanbe", Tr("Dushanbe"))
	checkZoneValid("+05:00", "Asia/Karachi", Tr("Karachi"))
	checkZoneValid("+05:00", "Asia/Oral", Tr("Oral"))
	checkZoneValid("+05:00", "Asia/Samarkand", Tr("Samarkand"))
	checkZoneValid("+05:00", "Asia/Tashkent", Tr("Tashkent"))
	checkZoneValid("+05:00", "Indian/Kerguelen", Tr("Kerguelen"))
	checkZoneValid("+05:00", "Indian/Maldives", Tr("Maldives"))

	checkZoneValid("+05:30", "Asia/Calcutta", Tr("Calcutta"))
	checkZoneValid("+05:30", "Asia/Colombo", Tr("Colombo"))
	checkZoneValid("+05:30", "Asia/Kolkata", Tr("Kolkata"))

	checkZoneValid("+05:45", "Asia/Kathmandu", Tr("Kathmandu"))
	//checkZoneValid("+05:45", "Asia/Katmandu", Tr("Katmandu"))

	checkZoneValid("+06:00", "Antarctica/Vostok", Tr("Vostok"))
	checkZoneValid("+06:00", "Asia/Almaty", Tr("Almaty"))
	checkZoneValid("+06:00", "Asia/Bishkek", Tr("Bishkek"))
	//checkZoneValid("+06:00", "Asia/Dacca", Tr("Dacca"))
	checkZoneValid("+06:00", "Asia/Dhaka", Tr("Dhaka"))
	checkZoneValid("+06:00", "Asia/Qyzylorda", Tr("Qyzylorda"))
	//checkZoneValid("+06:00", "Asia/Thimbu", Tr("Thimbu"))
	checkZoneValid("+06:00", "Asia/Thimphu", Tr("Thimphu"))
	checkZoneValid("+06:00", "Asia/Yekaterinburg", Tr("Yekaterinburg"))
	checkZoneValid("+06:00", "Indian/Chagos", Tr("Chagos"))

	checkZoneValid("+06:30", "Asia/Rangoon", Tr("Rangoon"))
	checkZoneValid("+06:30", "Indian/Cocos", Tr("Cocos"))

	checkZoneValid("+07:00", "Asia/Bangkok", Tr("Bangkok"))
	checkZoneValid("+07:00", "Asia/Ho_Chi_Minh", Tr("Ho Chi Minh"))
	checkZoneValid("+07:00", "Asia/Hovd", Tr("Hovd"))
	checkZoneValid("+07:00", "Asia/Jakarta", Tr("Jakarta"))
	checkZoneValid("+07:00", "Asia/Novokuznetsk", Tr("Novokuznetsk"))
	checkZoneValid("+07:00", "Asia/Novosibirsk", Tr("Novosibirsk"))
	checkZoneValid("+07:00", "Asia/Omsk", Tr("Omsk"))
	checkZoneValid("+07:00", "Asia/Phnom_Penh", Tr("Phnom Penh"))
	checkZoneValid("+07:00", "Asia/Pontianak", Tr("Pontianak"))
	checkZoneValid("+07:00", "Asia/Saigon", Tr("Saigon"))
	checkZoneValid("+07:00", "Asia/Vientiane", Tr("Vientiane"))
	checkZoneValid("+07:00", "Indian/Christmas", Tr("Christmas"))

	checkZoneValid("+08:00", "Asia/Brunei", Tr("Brunei"))
	checkZoneValid("+08:00", "Asia/Choibalsan", Tr("Choibalsan"))
	checkZoneValid("+08:00", "Asia/Chongqing", Tr("Chongqing"))
	//checkZoneValid("+08:00", "Asia/Chungking", Tr("Chungking"))
	checkZoneValid("+08:00", "Asia/Harbin", Tr("Harbin"))
	checkZoneValid("+08:00", "Asia/Hong_Kong", Tr("Hong Kong"))
	checkZoneValid("+08:00", "Asia/Kashgar", Tr("Kashgar"))
	checkZoneValid("+08:00", "Asia/Krasnoyarsk", Tr("Krasnoyarsk"))
	checkZoneValid("+08:00", "Asia/Kuala_Lumpur", Tr("Kuala Lumpur"))
	checkZoneValid("+08:00", "Asia/Kuching", Tr("Kuching"))
	checkZoneValid("+08:00", "Asia/Macao", Tr("Macao"))
	//checkZoneValid("+08:00", "Asia/Macau", Tr("Macau"))
	checkZoneValid("+08:00", "Asia/Makassar", Tr("Makassar"))
	checkZoneValid("+08:00", "Asia/Manila", Tr("Manila"))
	checkZoneValid("+08:00", "Asia/Shanghai", Tr("Shanghai"))
	checkZoneValid("+08:00", "Asia/Beijing", Tr("Beijing"))
	checkZoneValid("+08:00", "Asia/Singapore", Tr("Singapore"))
	checkZoneValid("+08:00", "Asia/Taipei", Tr("Taipei"))
	checkZoneValid("+08:00", "Asia/Ujung_Pandang", Tr("Ujung Pandang"))
	//checkZoneValid("+08:00", "Asia/Ulaanbaatar", Tr("Ulaanbaatar"))
	checkZoneValid("+08:00", "Asia/Ulan_Bator", Tr("Ulan Bator"))
	checkZoneValid("+08:00", "Asia/Urumqi", Tr("Urumqi"))
	checkZoneValid("+08:00", "Australia/Perth", Tr("Perth"))
	checkZoneValid("+08:00", "Australia/West", Tr("Australia/West"))
	//checkZoneValid("+08:00", "Hongkong", Tr("Hongkong"))
	checkZoneValid("+08:00", "PRC", Tr("PRC"))
	checkZoneValid("+08:00", "ROC", Tr("ROC"))
	//checkZoneValid("+08:00", "Singapore", Tr("Singapore"))

	checkZoneValid("+08:45", "Australia/Eucla", Tr("Eucla"))

	checkZoneValid("+09:00", "Asia/Dili", Tr("Dili"))
	checkZoneValid("+09:00", "Asia/Irkutsk", Tr("Irkutsk"))
	checkZoneValid("+09:00", "Asia/Jayapura", Tr("Jayapura"))
	checkZoneValid("+09:00", "Asia/Pyongyang", Tr("Pyongyang"))
	checkZoneValid("+09:00", "Asia/Seoul", Tr("Seoul"))
	checkZoneValid("+09:00", "Asia/Tokyo", Tr("Tokyo"))
	checkZoneValid("+09:00", "Japan", Tr("Japan"))
	checkZoneValid("+09:00", "Pacific/Palau", Tr("Palau"))
	checkZoneValid("+09:00", "ROK", Tr("ROK"))

	checkZoneValid("+09:30", "Australia/Adelaide", Tr("Adelaide"))
	checkZoneValid("+09:30", "Australia/Broken_Hill", Tr("Broke Hill"))
	checkZoneValid("+09:30", "Australia/Darwin", Tr("Darwin"))
	checkZoneValid("+09:30", "Australia/North", Tr("Australia/North"))
	checkZoneValid("+09:30", "Australia/South", Tr("Australia/South"))
	checkZoneValid("+09:30", "Australia/Yancowinna", Tr("Yancowinna"))

	checkZoneValid("+10:00", "Antarctica/DumontDUrville", Tr("DumontDUrville"))
	checkZoneValid("+10:00", "Asia/Khandyga", Tr("Khandyga"))
	checkZoneValid("+10:00", "Asia/Yakutsk", Tr("Yakutsk"))
	checkZoneValid("+10:00", "Australia/ACT", Tr("ACT"))
	checkZoneValid("+10:00", "Australia/Brisbane", Tr("Brisbane"))
	checkZoneValid("+10:00", "Australia/Canberra", Tr("Canberra"))
	checkZoneValid("+10:00", "Australia/Currie", Tr("Currie"))
	checkZoneValid("+10:00", "Australia/Hobart", Tr("Hobart"))
	checkZoneValid("+10:00", "Australia/Lindeman", Tr("Lindeman"))
	checkZoneValid("+10:00", "Australia/Melbourne", Tr("Melbourne"))
	checkZoneValid("+10:00", "Australia/NSW", Tr("NSW"))
	checkZoneValid("+10:00", "Australia/Queensland", Tr("Queensland"))
	checkZoneValid("+10:00", "Australia/Sydney", Tr("Sydney"))
	checkZoneValid("+10:00", "Australia/Tasmania", Tr("Tasmania"))
	checkZoneValid("+10:00", "Australia/Victoria", Tr("Victoria"))
	checkZoneValid("+10:00", "Pacific/Chuuk", Tr("Chuuk"))
	checkZoneValid("+10:00", "Pacific/Guam", Tr("Guam"))
	checkZoneValid("+10:00", "Pacific/Port_Moresby", Tr("Port Moresby"))
	checkZoneValid("+10:00", "Pacific/Saipan", Tr("Saipan"))
	checkZoneValid("+10:00", "Pacific/Truk", Tr("Truk"))
	checkZoneValid("+10:00", "Pacific/Yap", Tr("Yap"))

	checkZoneValid("+10:30", "Australia/LHI", Tr("LHI"))
	checkZoneValid("+10:30", "Australia/Lord_Howe", Tr("Lord Howe"))

	checkZoneValid("+11:00", "Antarctica/Casey", Tr("Casey"))
	checkZoneValid("+11:00", "Antarctica/Macquarie", Tr("Macquarie"))
	checkZoneValid("+11:00", "Asia/Sakhalin", Tr("Sakhalin"))
	checkZoneValid("+11:00", "Asia/Ust-Nera", Tr("Ust-Nera"))
	checkZoneValid("+11:00", "Asia/Vladivostok", Tr("Vladivostok"))
	checkZoneValid("+11:00", "Pacific/Efate", Tr("Efate"))
	checkZoneValid("+11:00", "Pacific/Guadalcanal", Tr("Guadalcanal"))
	checkZoneValid("+11:00", "Pacific/Kosrae", Tr("Kosrae"))
	checkZoneValid("+11:00", "Pacific/Noumea", Tr("Noumea"))
	checkZoneValid("+11:00", "Pacific/Pohnpei", Tr("Pohnpei"))
	//checkZoneValid("+11:00", "Pacific/Ponape", Tr("Ponape"))

	checkZoneValid("+11:30", "Pacific/Norfolk", Tr("Norfolk"))

	checkZoneValid("+12:00", "Antarctica/McMurdo", Tr("McMurdo"))
	checkZoneValid("+12:00", "Antarctica/South_Pole", Tr("South Pole"))
	checkZoneValid("+12:00", "Asia/Anadyr", Tr("Anadyr"))
	checkZoneValid("+12:00", "Asia/Kamchatka", Tr("Kamchatka"))
	checkZoneValid("+12:00", "Asia/Magadan", Tr("Magadan"))
	//checkZoneValid("+12:00", "Kwajalein", Tr("Kwajalein"))
	checkZoneValid("+12:00", "NZ", Tr("NZ"))
	checkZoneValid("+12:00", "Pacific/Auckland", Tr("Auckland"))
	checkZoneValid("+12:00", "Pacific/Fiji", Tr("Fiji"))
	checkZoneValid("+12:00", "Pacific/Funafuti", Tr("Funafuti"))
	checkZoneValid("+12:00", "Pacific/Kwajalein", Tr("Kwajalein"))
	checkZoneValid("+12:00", "Pacific/Majuro", Tr("Majuro"))
	checkZoneValid("+12:00", "Pacific/Nauru", Tr("Nauru"))
	checkZoneValid("+12:00", "Pacific/Tarawa", Tr("Tarawa"))
	checkZoneValid("+12:00", "Pacific/Wake", Tr("Wake"))
	checkZoneValid("+12:00", "Pacific/Wallis", Tr("Wallis"))

	checkZoneValid("+12:45", "NZ-CHAT", Tr("NZ-CHAT"))
	checkZoneValid("+12:45", "Pacific/Chatham", Tr("Chatham"))

	checkZoneValid("+13:00", "Pacific/Apia", Tr("Apia"))
	checkZoneValid("+13:00", "Pacific/Enderbury", Tr("Enderbury"))
	checkZoneValid("+13:00", "Pacific/Fakaofo", Tr("Fakaofo"))

	checkZoneValid("+13:00", "Pacific/Tongatapu", Tr("Tongatapu"))
}
