package main

import (
	"dlib"
)

var zoneCityMap = map[string]string{
	"Africa/Abidjan":                   dlib.Tr("Côte d'Ivoire (UTC+00) Abidjan"),
	"Africa/Accra":                     dlib.Tr("Ghana (UTC+00) Accra"),
	"Africa/Addis_Ababa":               dlib.Tr("Ethiopia (UTC+03) Addis Ababa"),
	"Africa/Algiers":                   dlib.Tr("Algeria (UTC+01) Algiers"),
	"Africa/Asmara":                    dlib.Tr("Eritrea (UTC+03) Asmara"),
	"Africa/Asmera":                    dlib.Tr("Eritrea (UTC+03) Asmera"),
	"Africa/Bamako":                    dlib.Tr("Mali (UTC+00) Bamako"),
	"Africa/Bangui":                    dlib.Tr("Central African Republic (UTC+01) Bangui"),
	"Africa/Banjul":                    dlib.Tr("The Gambia (UTC+00) Banjul"),
	"Africa/Bissau":                    dlib.Tr("Guinea-Bissau (UTC+00) Bissau"),
	"Africa/Blantyre":                  dlib.Tr("Malawi (UTC+02) Blantyre"),
	"Africa/Brazzaville":               dlib.Tr("Congo (UTC+01) Brazzaville"),
	"Africa/Bujumbura":                 dlib.Tr("Burundi (UTC+02) Bujumbura"),
	"Africa/Cairo":                     dlib.Tr("Egypt (UTC+02) Cairo"),
	"Africa/Casablanca":                dlib.Tr("Morocco (UTC+00) Casablanca"),
	"Africa/Ceuta":                     dlib.Tr("Spain (UTC+01) Ceuta"),
	"Africa/Conakry":                   dlib.Tr("Guinea (UTC+00) Conakry"),
	"Africa/Dakar":                     dlib.Tr("Senegal (UTC+00) Dakar"),
	"Africa/Dar_es_Salaam":             dlib.Tr("Tanzania (UTC+03) Dar es Salaam"),
	"Africa/Djibouti":                  dlib.Tr("Djibouti (UTC+03) Djibouti"),
	"Africa/Douala":                    dlib.Tr("Cameroon (UTC+01) Douala"),
	"Africa/El_Aaiun":                  dlib.Tr("Western Sahara (UTC+00) El Aaiun"),
	"Africa/Freetown":                  dlib.Tr("Sierra Leone (UTC+00) Freetown"),
	"Africa/Gaborone":                  dlib.Tr("Botswana (UTC+02) Gaborone"),
	"Africa/Harare":                    dlib.Tr("Zimbabwe (UTC+02) Harare"),
	"Africa/Johannesburg":              dlib.Tr("South Africa (UTC+02) Johannesburg"),
	"Africa/Juba":                      dlib.Tr("South Sudan (UTC+03) Juba"),
	"Africa/Kampala":                   dlib.Tr("Uganda (UTC+03) Kampala"),
	"Africa/Khartoum":                  dlib.Tr("Sudan (UTC+03) Khartoum"),
	"Africa/Kigali":                    dlib.Tr("Rwanda (UTC+02) Kigali"),
	"Africa/Kinshasa":                  dlib.Tr("Democratic Republic of the Congo (UTC+01) Kinshasa"),
	"Africa/Lagos":                     dlib.Tr("Nigeria (UTC+01) Lagos"),
	"Africa/Libreville":                dlib.Tr("Gabon (UTC+01) Libreville"),
	"Africa/Lome":                      dlib.Tr("Togo (UTC+00) Lome"),
	"Africa/Luanda":                    dlib.Tr("Angola (UTC+01) Luanda"),
	"Africa/Lubumbashi":                dlib.Tr("Democratic Republic of the Congo (UTC+02) Lubumbashi"),
	"Africa/Lusaka":                    dlib.Tr("Zambia (UTC+02) Lusaka"),
	"Africa/Malabo":                    dlib.Tr("Equatorial Guinea (UTC+01) Malabo"),
	"Africa/Maputo":                    dlib.Tr("Mozambique (UTC+02) Maputo"),
	"Africa/Maseru":                    dlib.Tr("Lesotho (UTC+02) Maseru"),
	"Africa/Mbabane":                   dlib.Tr("Swaziland (UTC+02) Mbabane"),
	"Africa/Mogadishu":                 dlib.Tr("Somalia (UTC+03) Mogadishu"),
	"Africa/Monrovia":                  dlib.Tr("Liberia (UTC+00) Monrovia"),
	"Africa/Nairobi":                   dlib.Tr("Kenya (UTC+03) Nairobi"),
	"Africa/Ndjamena":                  dlib.Tr("Chad (UTC+01) Ndjamena"),
	"Africa/Niamey":                    dlib.Tr("Niger (UTC+01) Niamey"),
	"Africa/Nouakchott":                dlib.Tr("Mauritania (UTC+00) Nouakchott"),
	"Africa/Ouagadougou":               dlib.Tr("Burkina Faso (UTC+00) Ouagadougou"),
	"Africa/Porto-Novo":                dlib.Tr("Benin (UTC+01) Porto Novo"),
	"Africa/Sao_Tome":                  dlib.Tr("São Tomé and Príncipe (UTC+00) Sao Tome"),
	"Africa/Timbuktu":                  dlib.Tr("Mali (UTC+00) Timbuktu"),
	"Africa/Tripoli":                   dlib.Tr("Libya (UTC+02) Tripoli"),
	"Africa/Tunis":                     dlib.Tr("Tunisia (UTC+01) Tunis"),
	"Africa/Windhoek":                  dlib.Tr("Namibia (UTC+01) Windhoek"),
	"America/Adak":                     dlib.Tr("USA (UTC−10) Adak"),
	"America/Anchorage":                dlib.Tr("USA (UTC−09) Anchorage"),
	"America/Anguilla":                 dlib.Tr("USA (UTC−04) Anguilla"),
	"America/Antigua":                  dlib.Tr("USA (UTC−04) Antigua"),
	"America/Araguaina":                dlib.Tr("USA (UTC−03) Araguaina"),
	"America/Argentina/Buenos_Aires":   dlib.Tr("Argentina (UTC−03) Buenos Aires"),
	"America/Argentina/Catamarca":      dlib.Tr("Argentina (UTC−03) Catamarca"),
	"America/Argentina/ComodRivadavia": dlib.Tr("Argentina (UTC−03) ComodRivadavia"),
	"America/Argentina/Cordoba":        dlib.Tr("Argentina (UTC−03) Cordoba"),
	"America/Argentina/Jujuy":          dlib.Tr("Argentina (UTC−03) Jujuy"),
	"America/Argentina/La_Rioja":       dlib.Tr("Argentina (UTC−03) La Rioja"),
	"America/Argentina/Mendoza":        dlib.Tr("Argentina (UTC−03) Mendoza"),
	"America/Argentina/Rio_Gallegos":   dlib.Tr("Argentina (UTC−03) Rio Gallegos"),
	"America/Argentina/Salta":          dlib.Tr("Argentina (UTC−03) Salta"),
	"America/Argentina/San_Juan":       dlib.Tr("Argentina (UTC−03) San Juan"),
	"America/Argentina/San_Luis":       dlib.Tr("Argentina (UTC−03) San Luis"),
	"America/Argentina/Tucuman":        dlib.Tr("Argentina (UTC−03) Tucuman"),
	"America/Argentina/Ushuaia":        dlib.Tr("Argentina (UTC−03) Ushuaia"),
	"America/Aruba":                    dlib.Tr("USA (UTC−04) Aruba"),
	"America/Asuncion":                 dlib.Tr("USA (UTC−04) Asuncion"),
	"America/Atikokan":                 dlib.Tr("Canada (UTC−05) Atikokan"),
	"America/Atka":                     dlib.Tr("USA (UTC−10) Atka"),
	"America/Bahia":                    dlib.Tr("Brazil (UTC−03) Bahia"),
	"America/Bahia_Banderas":           dlib.Tr("Mexico (UTC−06) Bahia Banderas"),
	"America/Barbados":                 dlib.Tr("USA (UTC−04) Barbados"),
	"America/Belem":                    dlib.Tr("USA (UTC−03) Belem"),
	"America/Belize":                   dlib.Tr("USA (UTC−06) Belize"),
	"America/Boa_Vista":                dlib.Tr("USA (UTC−04) Boa Vista"),
	"America/Bogota":                   dlib.Tr("USA (UTC−05) Bogota"),
	"America/Boise":                    dlib.Tr("USA (UTC−07) Boise"),
	"America/Buenos_Aires":             dlib.Tr("Argentina (UTC−03) Buenos Aires"),
	"America/Cambridge_Bay":            dlib.Tr("USA (UTC−07) Cambridge Bay"),
	"America/Campo_Grande":             dlib.Tr("USA (UTC−04) Campo Grande"),
	"America/Cancun":                   dlib.Tr("USA (UTC−06) Cancun"),
	"America/Caracas":                  dlib.Tr("Ecuador (UTC−03) Caracas"),
	"America/Cayenne":                  dlib.Tr("USA (UTC−03) Cayenne"),
	"America/Cayman":                   dlib.Tr("USA (UTC−05) Cayman"),
	"America/Chicago":                  dlib.Tr("USA (UTC−06) Chicago"),
	"America/Chihuahua":                dlib.Tr("Mexico (UTC−07) Chihuahua"),
	"America/Coral_Harbour":            dlib.Tr("USA (UTC−05) Coral Harbour"),
	"America/Cordoba":                  dlib.Tr("USA (UTC−03) Cordoba"),
	"America/Costa_Rica":               dlib.Tr("USA (UTC−06) Costa Rica"),
	"America/Creston":                  dlib.Tr("USA (UTC−07) Creston"),
	"America/Cuiaba":                   dlib.Tr("USA (UTC−04) Cuiaba"),
	"America/Curacao":                  dlib.Tr("USA (UTC−04) Curacao"),
	"America/Dawson":                   dlib.Tr("USA (UTC−08) Dawson"),
	"America/Dawson_Creek":             dlib.Tr("USA (UTC−07) Dawson Creek"),
	"America/Denver":                   dlib.Tr("USA (UTC−07) Denver"),
	"America/Detroit":                  dlib.Tr("USA (UTC−05) Detroit"),
	"America/Dominica":                 dlib.Tr("USA (UTC−04) Dominica"),
	"America/Edmonton":                 dlib.Tr("USA (UTC−07) Edmonton"),
	"America/Eirunepe":                 dlib.Tr("Brazil (UTC−04) Eirunepe"),
	"America/El_Salvador":              dlib.Tr("USA (UTC−06) El Salvador"),
	"America/Ensenada":                 dlib.Tr("USA (UTC−08) Ensenada"),
	"America/Fort_Wayne":               dlib.Tr("USA (UTC−05) Fort Wayne"),
	"America/Fortaleza":                dlib.Tr("USA (UTC−03) Fortaleza"),
	"America/Glace_Bay":                dlib.Tr("USA (UTC−04) Glace Bay"),
	"America/Godthab":                  dlib.Tr("Greenland (UTC−03) Godthab"),
	"America/Goose_Bay":                dlib.Tr("USA (UTC−04) Goose Bay"),
	"America/Grand_Turk":               dlib.Tr("USA (UTC−05) Grand Turk"),
	"America/Grenada":                  dlib.Tr("USA (UTC−04) Grenada"),
	"America/Guadeloupe":               dlib.Tr("Mexico (UTC−04) Guadeloupe"),
	"America/Guatemala":                dlib.Tr("Mexico (UTC−06) Guatemala"),
	"America/Guayaquil":                dlib.Tr("Ecuador (UTC−05) Guayaquil"),
	"America/Guyana":                   dlib.Tr("Mexico (UTC−04) Guyana"),
	"America/Halifax":                  dlib.Tr("USA (UTC−04) Halifax"),
	"America/Havana":                   dlib.Tr("USA (UTC−05) Havana"),
	"America/Hermosillo":               dlib.Tr("USA (UTC−07) Hermosillo"),
	"America/Indiana/Indianapolis":     dlib.Tr("USA (UTC−05) Indianapolis"),
	"America/Indiana/Knox":             dlib.Tr("USA (UTC−06) Knox"),
	"America/Indiana/Marengo":          dlib.Tr("USA (UTC−05) Marengo"),
	"America/Indiana/Petersburg":       dlib.Tr("USA (UTC−05) Petersburg"),
	"America/Indiana/Tell_City":        dlib.Tr("USA (UTC−06) Tell City"),
	"America/Indiana/Vevay":            dlib.Tr("USA (UTC−05) Vevay"),
	"America/Indiana/Vincennes":        dlib.Tr("USA (UTC−05) Vincennes"),
	"America/Indiana/Winamac":          dlib.Tr("USA (UTC−05) Winamac"),
	"America/Indianapolis":             dlib.Tr("USA (UTC−05) Indianapolis"),
	"America/Inuvik":                   dlib.Tr("Canada (UTC−07) Inuvik"),
	"America/Iqaluit":                  dlib.Tr("Canada (UTC−05) Iqaluit"),
	"America/Jamaica":                  dlib.Tr("USA (UTC−05) Jamaica"),
	"America/Jujuy":                    dlib.Tr("Argentina (UTC−03) Jujuy"),
	"America/Juneau":                   dlib.Tr("USA (UTC−09) Juneau"),
	"America/Kentucky/Louisville":      dlib.Tr("USA (UTC−05) Louisville"),
	"America/Kentucky/Monticello":      dlib.Tr("USA (UTC−05) Monticello"),
	"America/Knox_IN":                  dlib.Tr("USA (UTC−06) Knox IN"),
	"America/Kralendijk":               dlib.Tr("Caribbean Netherlands (UTC−04) Kralendijk"),
	"America/La_Paz":                   dlib.Tr("USA (UTC−04) La Paz"),
	"America/Lima":                     dlib.Tr("USA (UTC−05) Lima"),
	"America/Los_Angeles":              dlib.Tr("USA (UTC−08) Los Angeles"),
	"America/Louisville":               dlib.Tr("USA (UTC−05) Louisville"),
	"America/Lower_Princes":            dlib.Tr("Canada (UTC−04) Lower Princes"),
	"America/Maceio":                   dlib.Tr("Brazil (UTC−03) Maceio"),
	"America/Managua":                  dlib.Tr("Mexico (UTC−06) Managua"),
	"America/Manaus":                   dlib.Tr("USA (UTC−04) Manaus"),
	"America/Marigot":                  dlib.Tr("USA (UTC−04) Marigot"),
	"America/Martinique":               dlib.Tr("USA (UTC−04) Martinique"),
	"America/Matamoros":                dlib.Tr("Mexico (UTC−06) Matamoros"),
	"America/Mazatlan":                 dlib.Tr("USA (UTC−07) Mazatlan"),
	"America/Mendoza":                  dlib.Tr("USA (UTC−03) Mendoza"),
	"America/Menominee":                dlib.Tr("USA (UTC−06) Menominee"),
	"America/Merida":                   dlib.Tr("USA (UTC−06) Merida"),
	"America/Metlakatla":               dlib.Tr("USA (UTC−08) Metlakatla"),
	"America/Mexico_City":              dlib.Tr("USA (UTC−06) Mexico City"),
	"America/Miquelon":                 dlib.Tr("USA (UTC−03) Miquelon"),
	"America/Moncton":                  dlib.Tr("Canada (UTC−04) Moncton"),
	"America/Monterrey":                dlib.Tr("USA (UTC−06) Monterrey"),
	"America/Montevideo":               dlib.Tr("USA (UTC−03) Montevideo"),
	"America/Montreal":                 dlib.Tr("USA (UTC−05) Montreal"),
	"America/Montserrat":               dlib.Tr("USA (UTC−04) Montserrat"),
	"America/Nassau":                   dlib.Tr("USA (UTC−05) Nassau"),
	"America/New_York":                 dlib.Tr("USA (UTC−05) New York"),
	"America/Nipigon":                  dlib.Tr("Canada (UTC−05) Nipigon"),
	"America/Nome":                     dlib.Tr("USA (UTC−09) Nome"),
	"America/Noronha":                  dlib.Tr("Brazil (UTC−02) Noronha"),
	"America/North_Dakota/Beulah":      dlib.Tr("USA (UTC−06) Beulah"),
	"America/North_Dakota/Center":      dlib.Tr("USA (UTC−06) Center"),
	"America/North_Dakota/New_Salem":   dlib.Tr("USA (UTC−06) New Salem"),
	"America/Ojinaga":                  dlib.Tr("Mexico (UTC−07) Ojinaga"),
	"America/Panama":                   dlib.Tr("USA (UTC−05) Panama"),
	"America/Paramaribo":               dlib.Tr("Mexico (UTC−03) Paramaribo"),
	"America/Phoenix":                  dlib.Tr("USA (UTC−07) Phoenix"),
	"America/Port_of_Spain":            dlib.Tr("USA (UTC−04) Port of Spain"),
	"America/Port-au-Prince":           dlib.Tr("USA (UTC−05) Port au Prince"),
	"America/Porto_Acre":               dlib.Tr("Brazil (UTC−05) Porto Acre"),
	"America/Porto_Velho":              dlib.Tr("USA (UTC−04) Porto Velho"),
	"America/Puerto_Rico":              dlib.Tr("USA (UTC−04) Puerto Rico"),
	"America/Rainy_River":              dlib.Tr("USA (UTC−06) Rainy River"),
	"America/Recife":                   dlib.Tr("USA (UTC−03) Recife"),
	"America/Regina":                   dlib.Tr("USA (UTC−06) Regina"),
	"America/Resolute":                 dlib.Tr("USA (UTC−06) Resolute"),
	"America/Rio_Branco":               dlib.Tr("USA (UTC−05) Rio Branco"),
	"America/Rosario":                  dlib.Tr("USA (UTC−03) Rosario"),
	"America/Santa_Isabel":             dlib.Tr("USA (UTC−08) Santa Isabel"),
	"America/Santarem":                 dlib.Tr("USA (UTC−03) Santarem"),
	"America/Santiago":                 dlib.Tr("USA (UTC−04) Santiago"),
	"America/Santo_Domingo":            dlib.Tr("USA (UTC−04) Santo Domingo"),
	"America/Sao_Paulo":                dlib.Tr("USA (UTC−03) Sao Paulo"),
	"America/Shiprock":                 dlib.Tr("USA (UTC−07) Shiprock"),
	"America/Sitka":                    dlib.Tr("USA (UTC−09) Sitka"),
	"America/St_Barthelemy":            dlib.Tr("USA (UTC−04) St Barthelemy"),
	"America/St_Johns":                 dlib.Tr("USA (UTC−04) St Johns"),
	"America/St_Lucia":                 dlib.Tr("USA (UTC−04) St Lucia"),
	"America/St_Thomas":                dlib.Tr("USA (UTC−04) St Thomas"),
	"America/St_Vincent":               dlib.Tr("USA (UTC−04) St Vincent"),
	"America/Swift_Current":            dlib.Tr("Canada (UTC−06) Swift Current"),
	"America/Tegucigalpa":              dlib.Tr("Ecuador (UTC−06) Tegucigalpa"),
	"America/Thule":                    dlib.Tr("USA (UTC−04) Thule"),
	"America/Thunder_Bay":              dlib.Tr("USA (UTC−05) Thunder Bay"),
	"America/Tijuana":                  dlib.Tr("Mexico (UTC−08) Tijuana"),
	"America/Toronto":                  dlib.Tr("Canada (UTC−05) Toronto"),
	"America/Tortola":                  dlib.Tr("USA (UTC−04) Tortola"),
	"America/Vancouver":                dlib.Tr("USA (UTC−08) Vancouver"),
	"America/Virgin":                   dlib.Tr("USA (UTC−04) Virgin"),
	"America/Whitehorse":               dlib.Tr("USA (UTC−08) Whitehorse"),
	"America/Winnipeg":                 dlib.Tr("Canada (UTC−06) Winnipeg"),
	"America/Yakutat":                  dlib.Tr("USA (UTC−09) Yakutat"),
	"America/Yellowknife":              dlib.Tr("USA (UTC−07) Yellowknife"),
	"Antarctica/Casey":                 dlib.Tr("Antarctica (UTC+11) Casey"),
	"Antarctica/Davis":                 dlib.Tr("Antarctica (UTC+05) Davis"),
	"Antarctica/DumontDUrville":        dlib.Tr("Antarctica (UTC+10) DumontDUrville"),
	"Antarctica/Mawson":                dlib.Tr("Antarctica (UTC+05) Mawson"),
	"Antarctica/McMurdo":               dlib.Tr("Antarctica (UTC+12) McMurdo"),
	"Antarctica/Palmer":                dlib.Tr("Antarctica (UTC−04) Palmer"),
	"Antarctica/Rothera":               dlib.Tr("Antarctica (UTC−03) Rothera"),
	"Antarctica/South_Pole":            dlib.Tr("Antarctica (UTC+12) South Pole"),
	"Antarctica/Vostok":                dlib.Tr("Antarctica (UTC+06) Vostok"),
	"Arctic/Longyearbyen":              dlib.Tr("Svalbard and Jan Mayen (UTC+01) Longyearbyen"),
	"Asia/Aden":                        dlib.Tr("Yemen (UTC+03) Aden"),
	"Asia/Almaty":                      dlib.Tr("Kazakhstan (UTC+06) Almaty"),
	"Asia/Amman":                       dlib.Tr("Jordan (UTC+02) Amman"),
	"Asia/Anadyr":                      dlib.Tr("Russia (UTC+12) Anadyr"),
	"Asia/Aqtau":                       dlib.Tr("Kazakhstan (UTC+05) Aqtau"),
	"Asia/Aqtobe":                      dlib.Tr("Kazakhstan (UTC+05) Aqtobe"),
	"Asia/Ashgabat":                    dlib.Tr("Turkmenistan (UTC+05) Ashgabat"),
	"Asia/Ashkhabad":                   dlib.Tr("Turkmenistan (UTC+05) Ashkhabad"),
	"Asia/Baghdad":                     dlib.Tr("Iraq (UTC+03) Baghdad"),
	"Asia/Bahrain":                     dlib.Tr("Bahrain (UTC+03) Bahrain"),
	"Asia/Baku":                        dlib.Tr("Azerbaijan (UTC+04) Baku"),
	"Asia/Bangkok":                     dlib.Tr("Thailand (UTC+07) Bangkok"),
	"Asia/Beirut":                      dlib.Tr("Lebanon (UTC+02) Beirut"),
	"Asia/Bishkek":                     dlib.Tr("Kyrgyzstan (UTC+06) Bishkek"),
	"Asia/Brunei":                      dlib.Tr("Brunei (UTC+08) Brunei"),
	"Asia/Calcutta":                    dlib.Tr("India (UTC+08) Calcutta"),
	"Asia/Chongqing":                   dlib.Tr("China (UTC+08) Chongqing"),
	"Asia/Chungking":                   dlib.Tr("China (UTC+08) Chungking"),
	"Asia/Colombo":                     dlib.Tr("Sri Lanka (UTC+06) Colombo"),
	"Asia/Damascus":                    dlib.Tr("Syria (UTC+02) Damascus"),
	"Asia/Dhaka":                       dlib.Tr("Bangladesh (UTC+06) Dhaka"),
	"Asia/Dili":                        dlib.Tr("Timor-Leste (UTC+09) Dili"),
	"Asia/Dubai":                       dlib.Tr("Dubai - United Arab Emirates (UTC+04) Dubai"),
	"Asia/Dushanbe":                    dlib.Tr("Tajikistan (UTC+05) Dushanbe"),
	"Asia/Gaza":                        dlib.Tr("Gaza (UTC+02) Gaza"),
	"Asia/Harbin":                      dlib.Tr("China (UTC+08) Harbin"),
	"Asia/Hebron":                      dlib.Tr("Hebron (UTC+02) Hebron"),
	"Asia/Ho_Chi_Minh":                 dlib.Tr("Vietnam (UTC+07) Ho Chi Minh"),
	"Asia/Hong_Kong":                   dlib.Tr("Hong Kong (UTC+08) Hong Kong"),
	"Asia/Hovd":                        dlib.Tr("Mongolia (UTC+07) Hovd"),
	"Asia/Irkutsk":                     dlib.Tr("Russia (UTC+09) Irkutsk"),
	"Asia/Istanbul":                    dlib.Tr("Turkey (UTC+02) Istanbul"),
	"Asia/Jakarta":                     dlib.Tr("Indonesia (UTC+07) Jakarta"),
	"Asia/Jayapura":                    dlib.Tr("India (UTC+09) Jayapura"),
	"Asia/Jerusalem":                   dlib.Tr("Israel (UTC+02) Jerusalem"),
	"Asia/Kabul":                       dlib.Tr("Afghanistan (UTC+12) Kabul"),
	"Asia/Karachi":                     dlib.Tr("Pakistan (UTC+05) Karachi"),
	"Asia/Kashgar":                     dlib.Tr("China (UTC+08) Kashgar"),
	"Asia/Kathmandu":                   dlib.Tr("Nepal (UTC+08) Kathmandu"),
	"Asia/Kuala_Lumpur":                dlib.Tr("Malaysia (UTC+08) Kuala Lumpur"),
	"Asia/Kuching":                     dlib.Tr("Malaysia (UTC+08) Kuching"),
	"Asia/Kuwait":                      dlib.Tr("Kuwait (UTC+03) Kuwait"),
	"Asia/Macao":                       dlib.Tr("Macau (UTC+08) Macao"),
	"Asia/Macau":                       dlib.Tr("Macau (UTC+08) Macau"),
	"Asia/Magadan":                     dlib.Tr("Russia (UTC+12) Magadan"),
	"Asia/Makassar":                    dlib.Tr("Indonesia (UTC+08) Makassar"),
	"Asia/Manila":                      dlib.Tr("Philippines (UTC+08) Manila"),
	"Asia/Muscat":                      dlib.Tr("Oman (UTC+04) Muscat"),
	"Asia/Nicosia":                     dlib.Tr("Nicosia (UTC+02) Nicosia"),
	"Asia/Novokuznetsk":                dlib.Tr("Russia (UTC+07) Novokuznetsk"),
	"Asia/Novosibirsk":                 dlib.Tr("Russia (UTC+07) Novosibirsk"),
	"Asia/Omsk":                        dlib.Tr("Russia (UTC+07) Omsk"),
	"Asia/Oral":                        dlib.Tr("Kazakhstan (UTC+05) Oral"),
	"Asia/Phnom_Penh":                  dlib.Tr("Cambodia (UTC+07) Phnom Penh"),
	"Asia/Pontianak":                   dlib.Tr("Indonesia (UTC+07) Pontianak"),
	"Asia/Pyongyang":                   dlib.Tr("North Korea (UTC+09) Pyongyang"),
	"Asia/Qatar":                       dlib.Tr("Qatar (UTC+03) Qatar"),
	"Asia/Qyzylorda":                   dlib.Tr("Kazakhstan (UTC+06) Qyzylorda"),
	"Asia/Rangoon":                     dlib.Tr("Myanmar (Burma) (UTC+03) Rangoon"),
	"Asia/Saigon":                      dlib.Tr("Vietnam (UTC+07) Saigon"),
	"Asia/Sakhalin":                    dlib.Tr("Russia (UTC+11) Sakhalin"),
	"Asia/Samarkand":                   dlib.Tr("Uzbekistan (UTC+05) Samarkand"),
	"Asia/Seoul":                       dlib.Tr("South Korea (UTC+09) Seoul"),
	"Asia/Shanghai":                    dlib.Tr("China (UTC+08) Shanghai"),
	"Asia/Beijing":                     dlib.Tr("China (UTC+08) Beijing"),
	"Asia/Singapore":                   dlib.Tr("Singapore (UTC+08) Singapore"),
	"Asia/Taipei":                      dlib.Tr("Taiwan (UTC+08) Taipei"),
	"Asia/Tashkent":                    dlib.Tr("Uzbekistan (UTC+05) Tashkent"),
	"Asia/Tbilisi":                     dlib.Tr("Georgia (UTC+04) Tbilisi"),
	"Asia/Tehran":                      dlib.Tr("Iran (UTC+02) Tehran"),
	"Asia/Thimbu":                      dlib.Tr("Bhutan (UTC+06) Thimbu"),
	"Asia/Thimphu":                     dlib.Tr("Bhutan (UTC+06) Thimphu"),
	"Asia/Tokyo":                       dlib.Tr("Japan (UTC+09) Tokyo"),
	"Asia/Ujung_Pandang":               dlib.Tr("Indonesia (UTC+08) Ujung Pandang"),
	"Asia/Ulaanbaatar":                 dlib.Tr("Mongolia (UTC+08) Ulaanbaatar"),
	"Asia/Ulan_Bator":                  dlib.Tr("Mongolia (UTC+08) Ulan Bator"),
	"Asia/Urumqi":                      dlib.Tr("China (UTC+08) Urumqi"),
	"Asia/Vientiane":                   dlib.Tr("Laos (UTC+07) Vientiane"),
	"Asia/Vladivostok":                 dlib.Tr("Russia (UTC+11) Vladivostok"),
	"Asia/Yakutsk":                     dlib.Tr("Russia (UTC+10) Yakutsk"),
	"Asia/Yekaterinburg":               dlib.Tr("620000 (UTC+06) Yekaterinburg"),
	"Asia/Yerevan":                     dlib.Tr("Armenia (UTC+04) Yerevan"),
	"Atlantic/Bermuda":                 dlib.Tr("USA (UTC−04) Bermuda"),
	"Atlantic/Canary":                  dlib.Tr("USA (UTC+00) Canary"),
	"Atlantic/Cape_Verde":              dlib.Tr("Puerto Rico (UTC−01) Cape Verde"),
	"Atlantic/Madeira":                 dlib.Tr("USA (UTC+00) Madeira"),
	"Atlantic/Reykjavik":               dlib.Tr("Iceland (UTC+00) Reykjavik"),
	"Atlantic/South_Georgia":           dlib.Tr("USA (UTC−02) South Georgia"),
	"Atlantic/St_Helena":               dlib.Tr("USA (UTC+00) St Helena"),
	"Atlantic/Stanley":                 dlib.Tr("USA (UTC−03) Stanley"),
	"Australia/ACT":                    dlib.Tr("Australia (UTC+10) ACT"),
	"Australia/Adelaide":               dlib.Tr("Australia (UTC+10) Adelaide"),
	"Australia/Broken_Hill":            dlib.Tr("Australia (UTC+10) Broken Hill"),
	"Australia/Currie":                 dlib.Tr("Australia (UTC+10) Currie"),
	"Australia/Darwin":                 dlib.Tr("Australia (UTC+10) Darwin"),
	"Australia/Lindeman":               dlib.Tr("Australia (UTC+10) Lindeman"),
	"Australia/Lord_Howe":              dlib.Tr("Australia (UTC+11) Lord Howe"),
	"Australia/Melbourne":              dlib.Tr("Australia (UTC+10) Melbourne"),
	"Australia/North":                  dlib.Tr("Australia (UTC+10) North"),
	"Australia/Perth":                  dlib.Tr("Australia (UTC+08) Perth"),
	"Australia/Queensland":             dlib.Tr("Australia (UTC+10) Queensland"),
	"Australia/South":                  dlib.Tr("Australia (UTC+10) South"),
	"Australia/Tasmania":               dlib.Tr("Australia (UTC+10) Tasmania"),
	"Australia/Victoria":               dlib.Tr("Australia (UTC+10) Victoria"),
	"Australia/West":                   dlib.Tr("Australia (UTC+08) West"),
	"Australia/Yancowinna":             dlib.Tr("Australia (UTC−05) Yancowinna"),
	"Brazil/East":                      dlib.Tr("Brazil (UTC−03) East"),
	"Brazil/West":                      dlib.Tr("Brazil (UTC−04) West"),
	"Canada/Atlantic":                  dlib.Tr("Canada (UTC−04) Atlantic"),
	"Canada/Central":                   dlib.Tr("USA (UTC−06) Central"),
	"Canada/Eastern":                   dlib.Tr("Canada (UTC−05) Eastern"),
	"Canada/East-Saskatchewan":         dlib.Tr("Canada (UTC−06) East Saskatchewan"),
	"Canada/Mountain":                  dlib.Tr("Canada (UTC−07) Mountain"),
	"Canada/Newfoundland":              dlib.Tr("Canada (UTC−08) Newfoundland"),
	"Canada/Saskatchewan":              dlib.Tr("Canada (UTC−06) Saskatchewan"),
	"Canada/Yukon":                     dlib.Tr("Canada (UTC−08) Yukon"),
	"CET":                              dlib.Tr("USA (UTC+01) CET"),
	"Chile/Continental":                dlib.Tr("Chile (UTC−04) Continental"),
	"Chile/EasterIsland":               dlib.Tr("Chile (UTC−06) EasterIsland"),
	"Cuba":                             dlib.Tr("Cuba (UTC−05) Cuba"),
	"EET":                              dlib.Tr("USA (UTC+02) EET"),
	"Egypt":                            dlib.Tr("Egypt (UTC+02) Egypt"),
	"Eire":                             dlib.Tr("Ireland (UTC+00) Eire"),
	"EST":                              dlib.Tr("Uganda (UTC−05) EST"),
	"Europe/Amsterdam":                 dlib.Tr("The Netherlands (UTC+01) Amsterdam"),
	"Europe/Andorra":                   dlib.Tr("Andorra (UTC+01) Andorra"),
	"Europe/Athens":                    dlib.Tr("Greece (UTC+02) Athens"),
	"Europe/Belfast":                   dlib.Tr("UK (UTC+00) Belfast"),
	"Europe/Belgrade":                  dlib.Tr("Serbia (UTC+01) Belgrade"),
	"Europe/Berlin":                    dlib.Tr("Germany (UTC+01) Berlin"),
	"Europe/Bratislava":                dlib.Tr("Slovakia (UTC+01) Bratislava"),
	"Europe/Brussels":                  dlib.Tr("Belgium (UTC+01) Brussels"),
	"Europe/Bucharest":                 dlib.Tr("Romania (UTC+02) Bucharest"),
	"Europe/Budapest":                  dlib.Tr("Hungary (UTC+01) Budapest"),
	"Europe/Chisinau":                  dlib.Tr("Moldova (UTC+02) Chisinau"),
	"Europe/Copenhagen":                dlib.Tr("Denmark (UTC+01) Copenhagen"),
	"Europe/Dublin":                    dlib.Tr("Ireland (UTC+00) Dublin"),
	"Europe/Gibraltar":                 dlib.Tr("Gibraltar (UTC+01) Gibraltar"),
	"Europe/Guernsey":                  dlib.Tr("Guernsey (UTC+00) Guernsey"),
	"Europe/Helsinki":                  dlib.Tr("Finland (UTC+02) Helsinki"),
	"Europe/Isle_of_Man":               dlib.Tr("Isle of Man (UTC+00) Isle of Man"),
	"Europe/Istanbul":                  dlib.Tr("Turkey (UTC+02) Istanbul"),
	"Europe/Jersey":                    dlib.Tr("Jersey (UTC+00) Jersey"),
	"Europe/Kaliningrad":               dlib.Tr("Russia (UTC+03) Kaliningrad"),
	"Europe/Kiev":                      dlib.Tr("Ukraine (UTC+02) Kiev"),
	"Europe/Lisbon":                    dlib.Tr("Portugal (UTC+00) Lisbon"),
	"Europe/Ljubljana":                 dlib.Tr("Slovenia (UTC+01) Ljubljana"),
	"Europe/London":                    dlib.Tr("UK (UTC+00) London"),
	"Europe/Luxembourg":                dlib.Tr("Luxembourg (UTC+01) Luxembourg"),
	"Europe/Madrid":                    dlib.Tr("Spain (UTC+01) Madrid"),
	"Europe/Malta":                     dlib.Tr("Malta (UTC+01) Malta"),
	"Europe/Mariehamn":                 dlib.Tr("Aland Islands (UTC+02) Mariehamn"),
	"Europe/Minsk":                     dlib.Tr("Belarus (UTC+03) Minsk"),
	"Europe/Monaco":                    dlib.Tr("Monaco (UTC+01) Monaco"),
	"Europe/Moscow":                    dlib.Tr("Russia (UTC+04) Moscow"),
	"Europe/Nicosia":                   dlib.Tr("Italy (UTC+02) Nicosia"),
	"Europe/Oslo":                      dlib.Tr("Norway (UTC+01) Oslo"),
	"Europe/Paris":                     dlib.Tr("France (UTC+01) Paris"),
	"Europe/Podgorica":                 dlib.Tr("Montenegro (UTC+01) Podgorica"),
	"Europe/Prague":                    dlib.Tr("Czech Republic (UTC+01) Prague"),
	"Europe/Riga":                      dlib.Tr("Latvia (UTC+02) Riga"),
	"Europe/Rome":                      dlib.Tr("Italy (UTC+01) Rome"),
	"Europe/Samara":                    dlib.Tr("Russia (UTC+04) Samara"),
	"Europe/San_Marino":                dlib.Tr("San Marino (UTC+01) San Marino"),
	"Europe/Sarajevo":                  dlib.Tr("Bosnia and Herzegovina (UTC+01) Sarajevo"),
	"Europe/Simferopol":                dlib.Tr("Ukraine (UTC+02) Simferopol"),
	"Europe/Skopje":                    dlib.Tr("Macedonia (FYROM) (UTC+01) Skopje"),
	"Europe/Sofia":                     dlib.Tr("Bulgaria (UTC+02) Sofia"),
	"Europe/Stockholm":                 dlib.Tr("Sweden (UTC+01) Stockholm"),
	"Europe/Tallinn":                   dlib.Tr("Estonia (UTC+02) Tallinn"),
	"Europe/Tirane":                    dlib.Tr("Albania (UTC+01) Tirane"),
	"Europe/Tiraspol":                  dlib.Tr("Moldova (UTC+02) Tiraspol"),
	"Europe/Uzhgorod":                  dlib.Tr("Ukraine (UTC+02) Uzhgorod"),
	"Europe/Vaduz":                     dlib.Tr("Liechtenstein (UTC+01) Vaduz"),
	"Europe/Vatican":                   dlib.Tr("Vatican City (UTC+01) Vatican"),
	"Europe/Vienna":                    dlib.Tr("Austria (UTC+01) Vienna"),
	"Europe/Vilnius":                   dlib.Tr("Lithuania (UTC+02) Vilnius"),
	"Europe/Volgograd":                 dlib.Tr("Russia (UTC+04) Volgograd"),
	"Europe/Warsaw":                    dlib.Tr("Poland (UTC+01) Warsaw"),
	"Europe/Zagreb":                    dlib.Tr("Croatia (UTC+01) Zagreb"),
	"Europe/Zaporozhye":                dlib.Tr("Ukraine (UTC+02) Zaporozhye"),
	"Europe/Zurich":                    dlib.Tr("Switzerland (UTC+01) Zurich"),
	"GB":                               dlib.Tr("United Kingdom (UTC+00) GB"),
	"GB-Eire":                          dlib.Tr("Ireland (UTC+00) GB Eire"),
	"GMT":                              dlib.Tr("USA (UTC+00) GMT"),
	"GMT+0":                            dlib.Tr("Brazil (UTC+00) GMT+0"),
	"GMT0":                             dlib.Tr("Brazil (UTC+00) GMT0"),
	"GMT-0":                            dlib.Tr("Brazil (UTC+00) GMT 0"),
	"Greenwich":                        dlib.Tr("UK (UTC+00) Greenwich"),
	"Hongkong":                         dlib.Tr("Hong Kong (UTC+08) Hongkong"),
	"HST":                              dlib.Tr("Indonesia (UTC−10) HST"),
	"Iceland":                          dlib.Tr("Iceland (UTC+00) Iceland"),
	"Indian/Antananarivo":              dlib.Tr("Madagascar (UTC+03) Antananarivo"),
	"Indian/Chagos":                    dlib.Tr("British Indian Ocean Territory (UTC+06) Chagos"),
	"Indian/Christmas":                 dlib.Tr("Christmas Island (UTC+07) Christmas"),
	"Indian/Kerguelen":                 dlib.Tr("Grande Terre (UTC+05) Kerguelen"),
	"Indian/Mahe":                      dlib.Tr("Seychelles (UTC+04) Mahe"),
	"Indian/Maldives":                  dlib.Tr("Maldives (UTC+05) Maldives"),
	"Indian/Mauritius":                 dlib.Tr("India (UTC+04) Mauritius"),
	"Indian/Reunion":                   dlib.Tr("USA (UTC+04) Reunion"),
	"Iran":                             dlib.Tr("Iran (UTC+02) Iran"),
	"Jamaica":                          dlib.Tr("Jamaica (UTC−05) Jamaica"),
	"Japan":                            dlib.Tr("Japan (UTC+09) Japan"),
	"Kwajalein":                        dlib.Tr("RMI (UTC+12) Kwajalein"),
	"Libya":                            dlib.Tr("Libya (UTC+02) Libya"),
	"MET":                              dlib.Tr("France (UTC+01) MET"),
	"Mexico/BajaNorte":                 dlib.Tr("Mexico (UTC−08) BajaNorte"),
	"Mexico/BajaSur":                   dlib.Tr("Mexico (UTC−07) BajaSur"),
	"Mexico/General":                   dlib.Tr("Mexico (UTC−06) General"),
	"MST":                              dlib.Tr("The Netherlands (UTC−07) MST"),
	"Navajo":                           dlib.Tr("USA (UTC−07) Navajo"),
	"NZ":                               dlib.Tr("New Zealand (UTC+12) NZ"),
	"Pacific/Auckland":                 dlib.Tr("New Zealand (UTC+12) Auckland"),
	"Pacific/Chatham":                  dlib.Tr("USA (UTC+10) Chatham"),
	"Pacific/Easter":                   dlib.Tr("USA (UTC−06) Easter"),
	"Pacific/Efate":                    dlib.Tr("Vanuatu (UTC+11) Efate"),
	"Pacific/Enderbury":                dlib.Tr("Australia (UTC+13) Enderbury"),
	"Pacific/Fakaofo":                  dlib.Tr("Tokelau (UTC+13) Fakaofo"),
	"Pacific/Fiji":                     dlib.Tr("Fiji (UTC+12) Fiji"),
	"Pacific/Funafuti":                 dlib.Tr("Tuvalu (UTC+12) Funafuti"),
	"Pacific/Galapagos":                dlib.Tr("Australia (UTC−06) Galapagos"),
	"Pacific/Gambier":                  dlib.Tr("Australia (UTC−09) Gambier"),
	"Pacific/Guadalcanal":              dlib.Tr("Solomon Islands (UTC+11) Guadalcanal"),
	"Pacific/Guam":                     dlib.Tr("Guam (UTC+10) Guam"),
	"Pacific/Honolulu":                 dlib.Tr("Hawaii 96813 (UTC−10) Honolulu"),
	"Pacific/Johnston":                 dlib.Tr("USA (UTC−10) Johnston"),
	"Pacific/Kosrae":                   dlib.Tr("Australia (UTC+11) Kosrae"),
	"Pacific/Kwajalein":                dlib.Tr("RMI (UTC+12) Kwajalein"),
	"Pacific/Marquesas":                dlib.Tr("French Polynesia (UTC−11) Marquesas"),
	"Pacific/Nauru":                    dlib.Tr("Australia (UTC+12) Nauru"),
	"Pacific/Niue":                     dlib.Tr("Niue (UTC−11) Niue"),
	"Pacific/Norfolk":                  dlib.Tr("USA (UTC+11) Norfolk"),
	"Pacific/Palau":                    dlib.Tr("Australia (UTC+09) Palau"),
	"Pacific/Pitcairn":                 dlib.Tr("Australia (UTC−08) Pitcairn"),
	"Pacific/Pohnpei":                  dlib.Tr("Micronesia (UTC+11) Pohnpei"),
	"Pacific/Ponape":                   dlib.Tr("Micronesia (UTC+11) Ponape"),
	"Pacific/Port_Moresby":             dlib.Tr("Papua New Guinea (UTC+10) Port Moresby"),
	"Pacific/Rarotonga":                dlib.Tr("Australia (UTC−10) Rarotonga"),
	"Pacific/Saipan":                   dlib.Tr("CNMI (UTC+10) Saipan"),
	"Pacific/Samoa":                    dlib.Tr("USA (UTC−11) Samoa"),
	"Pacific/Tahiti":                   dlib.Tr("French Polynesia (UTC−10) Tahiti"),
	"Pacific/Tarawa":                   dlib.Tr("Kiribati (UTC+12) Tarawa"),
	"Pacific/Tongatapu":                dlib.Tr("Tonga (UTC+13) Tongatapu"),
	"Pacific/Truk":                     dlib.Tr("USA (UTC+10) Truk"),
	"Pacific/Wake":                     dlib.Tr("USA (UTC+12) Wake"),
	"Pacific/Wallis":                   dlib.Tr("Australia (UTC+12) Wallis"),
	"Poland":                           dlib.Tr("Poland (UTC+01) Poland"),
	"Portugal":                         dlib.Tr("Portugal (UTC+00) Portugal"),
	"PRC":                              dlib.Tr("USA (UTC+08) PRC"),
	"ROC":                              dlib.Tr("USA (UTC+08) ROC"),
	"ROK":                              dlib.Tr("Czech Republic (UTC+09) ROK"),
	"Turkey":                           dlib.Tr("Turkey (UTC+02) Turkey"),
	"UCT":                              dlib.Tr("South Africa (UTC+00) UCT"),
	"Universal":                        dlib.Tr("USA (UTC+00) Universal"),
	"US/Alaska":                        dlib.Tr("USA (UTC−09) Alaska"),
	"US/Aleutian":                      dlib.Tr("USA (UTC−10) Aleutian"),
	"US/Arizona":                       dlib.Tr("USA (UTC−07) Arizona"),
	"US/Central":                       dlib.Tr("USA (UTC−06) Central"),
	"US/Eastern":                       dlib.Tr("USA (UTC−05) Eastern"),
	"US/East-Indiana":                  dlib.Tr("USA (UTC−05) East Indiana"),
	"US/Hawaii":                        dlib.Tr("USA (UTC−10) Hawaii"),
	"US/Indiana-Starke":                dlib.Tr("USA (UTC−06) Indiana Starke"),
	"US/Michigan":                      dlib.Tr("USA (UTC−05) Michigan"),
	"US/Mountain":                      dlib.Tr("USA (UTC−07) Mountain"),
	"US/Pacific":                       dlib.Tr("USA (UTC−08) Pacific"),
	"US/Pacific-New":                   dlib.Tr("USA (UTC−08) Pacific New"),
	"US/Samoa":                         dlib.Tr("USA (UTC−11) Samoa"),
	"UTC":                              dlib.Tr("USA (UTC+00) UTC"),
	"WET":                              dlib.Tr("USA (UTC+00) WET"),
	"W-SU":                             dlib.Tr("WA (UTC+04) W SU"),
	"Zulu":                             dlib.Tr("USA (UTC+00) Zulu"),
}
