#ifndef BLUETOOTHCONSTANTS_H
#define BLUETOOTHCONSTANTS_H

#define POPUPWIDTH (200)
#define ITEMHEIGHT (30)
#define CONTROLHEIGHT (35)
#define LIGHTSUFFIX ("_dark.svg")
#define DARKSUFFIX (".svg")
#define MARGIN (12)
#define SWITCHBUTTONWIDTH (50)

#endif // BLUETOOTHCONSTANTS_H
