/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -c DBusEntryProxyer -p dbusentryproxyer dde.dock.EntryProxyer.xml
 *
 * qdbusxml2cpp is Copyright (C) 2015 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "dbusentryproxyer.h"

/*
 * Implementation of interface class DBusEntryProxyer
 */

DBusEntryProxyer::DBusEntryProxyer(const QString &path,QObject *parent)
    : QDBusAbstractInterface(staticServerPath(), path, staticInterfaceName(), QDBusConnection::sessionBus(), parent)
{
    qDBusRegisterMetaType<StringMap>();
}

DBusEntryProxyer::~DBusEntryProxyer()
{
}

