/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-dock/gschema/com.deepin.dde.dock.module.gschema.xml -a ./dde-dock/toolGenerate/qdbusxml2cpp/com.deepin.dde.dock.module.gschemaAdaptor -i ./dde-dock/toolGenerate/qdbusxml2cpp/com.deepin.dde.dock.module.gschema.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "./dde-dock/toolGenerate/qdbusxml2cpp/com.deepin.dde.dock.module.gschemaAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

