name: cppcheck
on:
  pull_request:
    types: [opened, reopened, synchronize, closed]

jobs:
  cppchceck:
    name: cppcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: myml/action-cppcheck
        with:
          github_token: ""
          repository: ""
          pull_request_id: ""
          cppcheck_file: ""
