name: cppcheck
on:
  push:

jobs:
  cppchceck:
    name: cppcheck
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: generate
        run: |
          sudo apt-get install -y cppcheck httpie
          accept="Accept:application/vnd.github.v3+json"
          url="https://api.github.com/repos/octocat/hello-world/pulls/42/comments"
          authorization='authorization:"Bearer $GITHUB_TOKEN"'
          cppcheck --enable=all --template="http POST $url $accept $authorization path={file} line={line} body=\"[{id}]({severity}) {message}\"" test.cpp 2>comments.bash
      - name: comments
        run: |
          cat comments.bash
